INSERT IGNORE INTO `pc_parts_picker`.gpu VALUES ('asus-geforce-rtx-3080-tuf-gaming', 'Asus', 'TUF GAMING', 'RTX 3080', '10', 'Asus GeForce RTX 3080 TUF GAMING');
INSERT IGNORE INTO `pc_parts_picker`.gpu VALUES ('asus-geforce-rtx-2060-dual-evo-oc', 'Asus', 'DUAL EVO OC', 'RTX 2060', '6 ', 'Asus GeForce RTX 2060 DUAL EVO OC');
INSERT IGNORE INTO `pc_parts_picker`.gpu VALUES ('msi-radeon-rx-580-armor-oc', 'MSI', 'ARMOR OC', 'RX 580', '8 ', 'MSI Radeon RX 580 ARMOR OC');
INSERT IGNORE INTO `pc_parts_picker`.gpu VALUES ('msi-radeon-rx-5700-xt-gaming-x', 'MSI', 'GAMING X', 'RX 5700 XT', '8 ', 'MSI Radeon RX 5700 XT GAMING X');
INSERT IGNORE INTO `pc_parts_picker`.gpu VALUES ('gigabyte-geforce-rtx-2070-windforce-2x', 'Gigabyte', 'WINDFORCE 2X', 'RTX 2070', '8 ', 'Gigabyte GeForce RTX 2070 WINDFORCE 2X');
INSERT IGNORE INTO `pc_parts_picker`.gpu VALUES ('msi-geforce-rtx-3070-gaming-x-trio', 'MSI', 'GAMING X TRIO', 'RTX 3070', '8 ', 'MSI GeForce RTX 3070 GAMING X TRIO');
INSERT IGNORE INTO `pc_parts_picker`.gpu VALUES ('msi-radeon-rx-5500-xt-mech-oc', 'MSI', 'MECH OC', 'RX 5500 XT', '8 ', 'MSI Radeon RX 5500 XT MECH OC');
INSERT IGNORE INTO `pc_parts_picker`.gpu VALUES ('gigabyte-radeon-rx-6800-xt-gv-r68xt-16gc-b', 'Gigabyte', 'GV-R68XT-16GC-B', 'RX 6800 XT', '16', 'Gigabyte Radeon RX 6800 XT GV-R68XT-16GC-B');
INSERT IGNORE INTO `pc_parts_picker`.gpu VALUES ('msi-geforce-rtx-2060-gaming-z', 'MSI', 'GAMING Z', 'RTX 2060', '6 ', 'MSI GeForce RTX 2060 GAMING Z');
INSERT IGNORE INTO `pc_parts_picker`.gpu VALUES ('msi-radeon-rx-570-armor-oc', 'MSI', 'ARMOR OC', 'RX 570', '8 ', 'MSI Radeon RX 570 ARMOR OC');
INSERT IGNORE INTO `pc_parts_picker`.gpu VALUES ('msi-geforce-rtx-3080-gaming-x-trio', 'MSI', 'GAMING X TRIO', 'RTX 3080', '10', 'MSI GeForce RTX 3080 GAMING X TRIO');
INSERT IGNORE INTO `pc_parts_picker`.gpu VALUES ('msi-radeon-rx-5700-xt-mech-oc', 'MSI', 'MECH OC', 'RX 5700 XT', '8 ', 'MSI Radeon RX 5700 XT MECH OC');
INSERT IGNORE INTO `pc_parts_picker`.gpu VALUES ('gigabyte-geforce-rtx-3070-gaming-oc', 'Gigabyte', 'GAMING OC', 'RTX 3070', '8 ', 'Gigabyte GeForce RTX 3070 GAMING OC');
INSERT IGNORE INTO `pc_parts_picker`.gpu VALUES ('asus-radeon-rx-5700-xt-strix-gaming-oc', 'Asus', 'STRIX GAMING OC', 'RX 5700 XT', '8 ', 'Asus Radeon RX 5700 XT STRIX GAMING OC');
INSERT IGNORE INTO `pc_parts_picker`.gpu VALUES ('asus-geforce-rtx-3080-strix-gaming-oc', 'Asus', 'STRIX GAMING OC', 'RTX 3080', '10', 'Asus GeForce RTX 3080 STRIX GAMING OC');
INSERT IGNORE INTO `pc_parts_picker`.gpu VALUES ('asus-geforce-rtx-3070-strix-gaming', 'Asus', 'STRIX GAMING', 'RTX 3070', '8 ', 'Asus GeForce RTX 3070 STRIX GAMING');
INSERT IGNORE INTO `pc_parts_picker`.gpu VALUES ('gigabyte-radeon-rx-5700-xt-gaming-oc', 'Gigabyte', 'GAMING OC', 'RX 5700 XT', '8 ', 'Gigabyte Radeon RX 5700 XT GAMING OC');
INSERT IGNORE INTO `pc_parts_picker`.gpu VALUES ('msi-geforce-rtx-2080-super-gaming-x-trio', 'MSI', 'GAMING X TRIO', 'RTX 2080 SUPER', '8 ', 'MSI GeForce RTX 2080 SUPER GAMING X TRIO');
INSERT IGNORE INTO `pc_parts_picker`.gpu VALUES ('msi-geforce-rtx-3070-ventus-3x-oc', 'MSI', 'VENTUS 3X OC', 'RTX 3070', '8 ', 'MSI GeForce RTX 3070 VENTUS 3X OC');
INSERT IGNORE INTO `pc_parts_picker`.gpu VALUES ('asus-geforce-rtx-3090-strix-gaming-oc', 'Asus', 'STRIX GAMING OC', 'RTX 3090', '24', 'Asus GeForce RTX 3090 STRIX GAMING OC');
INSERT IGNORE INTO `pc_parts_picker`.gpu VALUES ('msi-geforce-rtx-3060-ti-gaming-x-trio', 'MSI', 'GAMING X TRIO', 'RTX 3060 Ti', '8 ', 'MSI GeForce RTX 3060 Ti GAMING X TRIO');
INSERT IGNORE INTO `pc_parts_picker`.gpu VALUES ('msi-geforce-rtx-3070-ventus-2x-oc', 'MSI', 'VENTUS 2X OC', 'RTX 3070', '8 ', 'MSI GeForce RTX 3070 VENTUS 2X OC');
INSERT IGNORE INTO `pc_parts_picker`.gpu VALUES ('gigabyte-geforce-rtx-3060-ti-aorus-master', 'Gigabyte', 'AORUS MASTER', 'RTX 3060 Ti', '8 ', 'Gigabyte GeForce RTX 3060 Ti AORUS MASTER');
INSERT IGNORE INTO `pc_parts_picker`.gpu VALUES ('gigabyte-geforce-rtx-2060-oc', 'Gigabyte', 'OC', 'RTX 2060', '6 ', 'Gigabyte GeForce RTX 2060 OC');
INSERT IGNORE INTO `pc_parts_picker`.gpu VALUES ('asus-geforce-rtx-3070-tuf-gaming-oc', 'Asus', 'TUF GAMING OC', 'RTX 3070', '8 ', 'Asus GeForce RTX 3070 TUF GAMING OC');
INSERT IGNORE INTO `pc_parts_picker`.gpu VALUES ('msi-geforce-rtx-3060-ti-ventus-2x-oc', 'MSI', 'VENTUS 2X OC', 'RTX 3060 Ti', '8 ', 'MSI GeForce RTX 3060 Ti VENTUS 2X OC');
INSERT IGNORE INTO `pc_parts_picker`.gpu VALUES ('msi-geforce-rtx-2060-ventus-xs-oc', 'MSI', 'VENTUS XS OC', 'RTX 2060', '6 ', 'MSI GeForce RTX 2060 VENTUS XS OC');
INSERT IGNORE INTO `pc_parts_picker`.gpu VALUES ('gigabyte-radeon-rx-6800-gv-r68-16gc-b', 'Gigabyte', 'GV-R68-16GC-B', 'RX 6800', '16', 'Gigabyte Radeon RX 6800 GV-R68-16GC-B');
INSERT IGNORE INTO `pc_parts_picker`.gpu VALUES ('gigabyte-geforce-rtx-3060-ti-gaming-oc', 'Gigabyte', 'GAMING OC', 'RTX 3060 Ti', '8 ', 'Gigabyte GeForce RTX 3060 Ti GAMING OC');
INSERT IGNORE INTO `pc_parts_picker`.gpu VALUES ('msi-geforce-rtx-3080-ventus-3x-oc', 'MSI', 'VENTUS 3X OC', 'RTX 3080', '10', 'MSI GeForce RTX 3080 VENTUS 3X OC');
INSERT IGNORE INTO `pc_parts_picker`.gpu VALUES ('gigabyte-radeon-rx-580-gaming-8g', 'Gigabyte', 'GAMING 8G', 'RX 580', '8 ', 'Gigabyte Radeon RX 580 GAMING 8G');
INSERT IGNORE INTO `pc_parts_picker`.gpu VALUES ('gigabyte-geforce-rtx-3060-ti-eagle-oc', 'Gigabyte', 'EAGLE OC', 'RTX 3060 Ti', '8 ', 'Gigabyte GeForce RTX 3060 Ti EAGLE OC');
INSERT IGNORE INTO `pc_parts_picker`.gpu VALUES ('gigabyte-geforce-rtx-3080-vision-oc', 'Gigabyte', 'Vision OC', 'RTX 3080', '10', 'Gigabyte GeForce RTX 3080 Vision OC');
INSERT IGNORE INTO `pc_parts_picker`.gpu VALUES ('gigabyte-geforce-rtx-3070-aorus-master', 'Gigabyte', 'AORUS MASTER', 'RTX 3070', '8 ', 'Gigabyte GeForce RTX 3070 AORUS MASTER');
INSERT IGNORE INTO `pc_parts_picker`.gpu VALUES ('zotac-geforce-rtx-3070-gaming-twin-edge-oc', 'Zotac', 'GAMING Twin Edge OC', 'RTX 3070', '8 ', 'Zotac GeForce RTX 3070 GAMING Twin Edge OC');
INSERT IGNORE INTO `pc_parts_picker`.gpu VALUES ('gigabyte-geforce-rtx-2070-super-gaming-oc-3x', 'Gigabyte', 'GAMING OC 3X', 'RTX 2070 SUPER', '8 ', 'Gigabyte GeForce RTX 2070 SUPER GAMING OC 3X');
INSERT IGNORE INTO `pc_parts_picker`.gpu VALUES ('asus-radeon-rx-570-strix-gaming-oc', 'Asus', 'STRIX GAMING OC', 'RX 570', '8 ', 'Asus Radeon RX 570 STRIX GAMING OC');
INSERT IGNORE INTO `pc_parts_picker`.gpu VALUES ('asus-geforce-rtx-2070-super-dual-evo-oc', 'Asus', 'DUAL EVO OC', 'RTX 2070 SUPER', '8 ', 'Asus GeForce RTX 2070 SUPER DUAL EVO OC');
INSERT IGNORE INTO `pc_parts_picker`.gpu VALUES ('asus-radeon-rx-580-dual', 'Asus', 'DUAL', 'RX 580', '8 ', 'Asus Radeon RX 580 DUAL');
INSERT IGNORE INTO `pc_parts_picker`.gpu VALUES ('msi-geforce-rtx-2060-super-gaming-x', 'MSI', 'GAMING X', 'RTX 2060 SUPER', '8 ', 'MSI GeForce RTX 2060 SUPER GAMING X');
INSERT IGNORE INTO `pc_parts_picker`.gpu VALUES ('msi-geforce-rtx-3090-gaming-x-trio', 'MSI', 'GAMING X TRIO', 'RTX 3090', '24', 'MSI GeForce RTX 3090 GAMING X TRIO');
INSERT IGNORE INTO `pc_parts_picker`.gpu VALUES ('asus-geforce-rtx-3090-tuf-gaming-oc', 'Asus', 'TUF GAMING OC', 'RTX 3090', '24', 'Asus GeForce RTX 3090 TUF GAMING OC');
INSERT IGNORE INTO `pc_parts_picker`.gpu VALUES ('gigabyte-geforce-rtx-2070-super-windforce-oc-3x', 'Gigabyte', 'WINDFORCE OC 3X', 'RTX 2070 SUPER', '8 ', 'Gigabyte GeForce RTX 2070 SUPER WINDFORCE OC 3X');
INSERT IGNORE INTO `pc_parts_picker`.gpu VALUES ('asus-geforce-rtx-3080-tuf-gaming-oc', 'Asus', 'TUF GAMING OC', 'RTX 3080', '10', 'Asus GeForce RTX 3080 TUF GAMING OC');
INSERT IGNORE INTO `pc_parts_picker`.gpu VALUES ('gigabyte-geforce-rtx-3070-vision-oc', 'Gigabyte', 'Vision OC', 'RTX 3070', '8 ', 'Gigabyte GeForce RTX 3070 Vision OC');
INSERT IGNORE INTO `pc_parts_picker`.gpu VALUES ('msi-geforce-rtx-2070-super-ventus-gp-oc', 'MSI', 'VENTUS GP OC', 'RTX 2070 SUPER', '8 ', 'MSI GeForce RTX 2070 SUPER VENTUS GP OC');
INSERT IGNORE INTO `pc_parts_picker`.gpu VALUES ('asus-geforce-rtx-3080-strix-gaming', 'Asus', 'STRIX GAMING', 'RTX 3080', '10', 'Asus GeForce RTX 3080 STRIX GAMING');
INSERT IGNORE INTO `pc_parts_picker`.gpu VALUES ('msi-radeon-rx-5500-xt-gaming-x', 'MSI', 'GAMING X', 'RX 5500 XT', '8 ', 'MSI Radeon RX 5500 XT GAMING X');
INSERT IGNORE INTO `pc_parts_picker`.gpu VALUES ('gigabyte-geforce-rtx-3070-eagle', 'Gigabyte', 'EAGLE', 'RTX 3070', '8 ', 'Gigabyte GeForce RTX 3070 EAGLE');
INSERT IGNORE INTO `pc_parts_picker`.gpu VALUES ('asus-geforce-rtx-2060-phoenix-fan', 'Asus', 'Phoenix Fan', 'RTX 2060', '6 ', 'Asus GeForce RTX 2060 Phoenix Fan');
INSERT IGNORE INTO `pc_parts_picker`.gpu VALUES ('asus-geforce-rtx-2060-tuf-oc', 'Asus', 'TUF OC', 'RTX 2060', '6 ', 'Asus GeForce RTX 2060 TUF OC');
INSERT IGNORE INTO `pc_parts_picker`.gpu VALUES ('gigabyte-geforce-rtx-3080-gaming-oc', 'Gigabyte', 'GAMING OC', 'RTX 3080', '10', 'Gigabyte GeForce RTX 3080 GAMING OC');
