INSERT IGNORE INTO `pc_parts_picker`.hdd VALUES ('seagate-firecuda-1024-2.5sata', 'Seagate', 'FireCuda', '2.5 SATA', '1 TB', 'HDD Seagate FireCuda 1 TB');
INSERT IGNORE INTO `pc_parts_picker`.hdd VALUES ('seagate-ironwolf-pro-14336-3.5sata', 'Seagate', 'IronWolf Pro', '3.5 SATA', '14 TB', 'HDD Seagate IronWolf Pro 14 TB');
INSERT IGNORE INTO `pc_parts_picker`.hdd VALUES ('wd-re-1024-3.5sata', 'Western Digital', 'Re', '3.5 SATA', '1 TB', 'HDD Western Digital Re 1 TB');
INSERT IGNORE INTO `pc_parts_picker`.hdd VALUES ('wd-re-2048-3.5sata', 'Western Digital', 'RE', '3.5 SATA', '2 TB', 'HDD Western Digital RE 2 TB');
INSERT IGNORE INTO `pc_parts_picker`.hdd VALUES ('wd-re-2048-3.5sata', 'Western Digital', 'RE', '3.5 SATA', '2 TB', 'HDD Western Digital RE 2 TB');
INSERT IGNORE INTO `pc_parts_picker`.hdd VALUES ('wd-re-3072-3.5sata', 'Western Digital', 'RE', '3.5 SATA', '3 TB', 'HDD Western Digital RE 3 TB');
INSERT IGNORE INTO `pc_parts_picker`.hdd VALUES ('seagate-pipeline-hd-1024-3.5sata', 'Seagate', 'Pipeline HD', '3.5 SATA', '1 TB', 'HDD Seagate Pipeline HD 1 TB');
INSERT IGNORE INTO `pc_parts_picker`.hdd VALUES ('seagate-skyhawk-ai-10240-3.5sata', 'Seagate', 'SkyHawk AI', '3.5 SATA', '10 TB', 'HDD Seagate SkyHawk AI 10 TB');
INSERT IGNORE INTO `pc_parts_picker`.hdd VALUES ('wd-re-4096-3.5sata', 'Western Digital', 'RE', '3.5 SATA', '4 TB', 'HDD Western Digital RE 4 TB');
INSERT IGNORE INTO `pc_parts_picker`.hdd VALUES ('seagate-skyhawk-ai-10240-3.5sata', 'Seagate', 'Skyhawk AI', '3.5 SATA', '10 TB', 'HDD Seagate Skyhawk AI 10 TB');
INSERT IGNORE INTO `pc_parts_picker`.hdd VALUES ('seagate-pipeline-hd-2048-3.5sata', 'Seagate', 'Pipeline HD', '3.5 SATA', '2 TB', 'HDD Seagate Pipeline HD 2 TB');
INSERT IGNORE INTO `pc_parts_picker`.hdd VALUES ('seagate-pipeline-hd-1024-3.5sata', 'Seagate', 'Pipeline HD', '3.5 SATA', '1 TB', 'HDD Seagate Pipeline HD 1 TB');
INSERT IGNORE INTO `pc_parts_picker`.hdd VALUES ('seagate-barracuda-4096-3.5sata', 'Seagate', 'BarraCuda', '3.5 SATA', '4 TB', 'HDD Seagate BarraCuda 4 TB');
INSERT IGNORE INTO `pc_parts_picker`.hdd VALUES ('seagate-ironwolf-pro-4096-3.5sata', 'Seagate', 'IronWolf Pro', '3.5 SATA', '4 TB', 'HDD Seagate IronWolf Pro 4 TB');
INSERT IGNORE INTO `pc_parts_picker`.hdd VALUES ('seagate-ironwolf-pro-16384-3.5sata', 'Seagate', 'IronWolf Pro', '3.5 SATA', '16 TB', 'HDD Seagate IronWolf Pro 16 TB');
INSERT IGNORE INTO `pc_parts_picker`.hdd VALUES ('seagate-barracuda-3072-3.5sata', 'Seagate', 'Barracuda', '3.5 SATA', '3 TB', 'HDD Seagate Barracuda 3 TB');
INSERT IGNORE INTO `pc_parts_picker`.hdd VALUES ('wd-re4-1024-3.5sata', 'Western Digital', 'RE4', '3.5 SATA', '1 TB', 'HDD Western Digital RE4 1 TB');
INSERT IGNORE INTO `pc_parts_picker`.hdd VALUES ('seagate-barracuda-6144-3.5sata', 'Seagate', 'Barracuda', '3.5 SATA', '6 TB', 'HDD Seagate Barracuda 6 TB');
INSERT IGNORE INTO `pc_parts_picker`.hdd VALUES ('seagate-ironwolf-pro-8192-3.5sata', 'Seagate', 'IronWolf Pro', '3.5 SATA', '8 TB', 'HDD Seagate IronWolf Pro 8 TB');
INSERT IGNORE INTO `pc_parts_picker`.hdd VALUES ('seagate-ironwolf-pro-10240-3.5sata', 'Seagate', 'IronWolf Pro', '3.5 SATA', '10 TB', 'HDD Seagate IronWolf Pro 10 TB');
INSERT IGNORE INTO `pc_parts_picker`.hdd VALUES ('seagate-ironwolf-pro-6144-3.5sata', 'Seagate', 'IronWolf Pro', '3.5 SATA', '6 TB', 'HDD Seagate IronWolf Pro 6 TB');
INSERT IGNORE INTO `pc_parts_picker`.hdd VALUES ('seagate-barracuda-4096-3.5sata', 'Seagate', 'BarraCuda', '3.5 SATA', '4 TB', 'HDD Seagate BarraCuda 4 TB');
INSERT IGNORE INTO `pc_parts_picker`.hdd VALUES ('seagate-ironwolf-pro-12288-3.5sata', 'Seagate', 'IronWolf Pro', '3.5 SATA', '12 TB', 'HDD Seagate IronWolf Pro 12 TB');
INSERT IGNORE INTO `pc_parts_picker`.hdd VALUES ('seagate-ironwolf-pro-4096-3.5sata', 'Seagate', 'IronWolf Pro', '3.5 SATA', '4 TB', 'HDD Seagate IronWolf Pro 4 TB');
INSERT IGNORE INTO `pc_parts_picker`.hdd VALUES ('seagate-ironwolf-pro-10240-3.5sata', 'Seagate', 'IronWolf Pro', '3.5 SATA', '10 TB', 'HDD Seagate IronWolf Pro 10 TB');
INSERT IGNORE INTO `pc_parts_picker`.hdd VALUES ('seagate-pipeline-hd-500-3.5sata', 'Seagate', 'Pipeline HD', '3.5 SATA', '500 GB', 'HDD Seagate Pipeline HD 500 GB');
INSERT IGNORE INTO `pc_parts_picker`.hdd VALUES ('seagate-firecuda-500-2.5sata', 'Seagate', 'FireCuda', '2.5 SATA', '500 GB', 'HDD Seagate FireCuda 500 GB');
INSERT IGNORE INTO `pc_parts_picker`.hdd VALUES ('wd-re4-2048-3.5sata', 'Western Digital', 'RE4', '3.5 SATA', '2 TB', 'HDD Western Digital RE4 2 TB');
INSERT IGNORE INTO `pc_parts_picker`.hdd VALUES ('seagate-ironwolf-pro-6144-3.5sata', 'Seagate', 'IronWolf Pro', '3.5 SATA', '6 TB', 'HDD Seagate IronWolf Pro 6 TB');
INSERT IGNORE INTO `pc_parts_picker`.hdd VALUES ('seagate-ironwolf-pro-8192-3.5sata', 'Seagate', 'IronWolf Pro', '3.5 SATA', '8 TB', 'HDD Seagate IronWolf Pro 8 TB');
INSERT IGNORE INTO `pc_parts_picker`.hdd VALUES ('seagate-skyhawk-ai-8192-3.5sata', 'Seagate', 'Skyhawk AI', '3.5 SATA', '8 TB', 'HDD Seagate Skyhawk AI 8 TB');
INSERT IGNORE INTO `pc_parts_picker`.hdd VALUES ('wd-black2-1024-2.5sata', 'Western Digital', 'Black2', '2.5 SATA', '1 TB', 'HDD Western Digital Black2 1 TB');
INSERT IGNORE INTO `pc_parts_picker`.hdd VALUES ('seagate-ironwolf-pro-12288-3.5sata', 'Seagate', 'IronWolf Pro', '3.5 SATA', '12 TB', 'HDD Seagate IronWolf Pro 12 TB');
INSERT IGNORE INTO `pc_parts_picker`.hdd VALUES ('seagate-barracuda-3072-3.5sata', 'Seagate', 'Barracuda', '3.5 SATA', '3 TB', 'HDD Seagate Barracuda 3 TB');
INSERT IGNORE INTO `pc_parts_picker`.hdd VALUES ('wd-re4-2048-3.5sata', 'Western Digital', 'RE4', '3.5 SATA', '2 TB', 'HDD Western Digital RE4 2 TB');
INSERT IGNORE INTO `pc_parts_picker`.hdd VALUES ('wd-se-1024-3.5sata', 'Western Digital', 'Se', '3.5 SATA', '1 TB', 'HDD Western Digital Se 1 TB');
INSERT IGNORE INTO `pc_parts_picker`.hdd VALUES ('seagate-ironwolf-pro-8192-3.5sata', 'Seagate', 'IronWolf Pro', '3.5 SATA', '8 TB', 'HDD Seagate IronWolf Pro 8 TB');
INSERT IGNORE INTO `pc_parts_picker`.hdd VALUES ('wd-re-500-3.5sata', 'Western Digital', 'Re', '3.5 SATA', '500 GB', 'HDD Western Digital Re 500 GB');
INSERT IGNORE INTO `pc_parts_picker`.hdd VALUES ('seagate-ironwolf-pro-6144-3.5sata', 'Seagate', 'IronWolf Pro', '3.5 SATA', '6 TB', 'HDD Seagate IronWolf Pro 6 TB');
INSERT IGNORE INTO `pc_parts_picker`.hdd VALUES ('wd-re4-2048-3.5sata', 'Western Digital', 'RE4', '3.5 SATA', '2 TB', 'HDD Western Digital RE4 2 TB');
