INSERT IGNORE INTO `pc_parts_picker`.hdd VALUES ('seagate-barracuda-compute-2048-3.5sata', 'Seagate', 'Barracuda Compute', '3.5 SATA', '2 TB', 'HDD Seagate Barracuda Compute 2 TB');
INSERT IGNORE INTO `pc_parts_picker`.hdd VALUES ('wd-caviar-blue-1024-3.5sata', 'WD', 'Caviar Blue', '3.5 SATA', '1 TB', 'HDD WD Caviar Blue 1 TB');
INSERT IGNORE INTO `pc_parts_picker`.hdd VALUES ('seagate-barracuda-1024-3.5sata', 'Seagate', 'BarraCuda', '3.5 SATA', '1 TB', 'HDD Seagate BarraCuda 1 TB');
INSERT IGNORE INTO `pc_parts_picker`.hdd VALUES ('seagate-barracuda-4096-3.5sata', 'Seagate', 'BarraCuda', '3.5 SATA', '4 TB', 'HDD Seagate BarraCuda 4 TB');
INSERT IGNORE INTO `pc_parts_picker`.hdd VALUES ('wd-blue-2048-3.5sata', 'WD', 'Blue', '3.5 SATA', '2 TB', 'HDD WD Blue 2 TB');
INSERT IGNORE INTO `pc_parts_picker`.hdd VALUES ('wd-gold-18432-3.5sata', 'WD', 'Gold', '3.5 SATA', '18 TB', 'HDD WD Gold 18 TB');
INSERT IGNORE INTO `pc_parts_picker`.hdd VALUES ('wd-black-4096-3.5sata', 'WD', 'Black', '3.5 SATA', '4 TB', 'HDD WD Black 4 TB');
INSERT IGNORE INTO `pc_parts_picker`.hdd VALUES ('seagate-barracuda-compute-2048-3.5sata', 'Seagate', 'Barracuda Compute', '3.5 SATA', '2 TB', 'HDD Seagate Barracuda Compute 2 TB');
INSERT IGNORE INTO `pc_parts_picker`.hdd VALUES ('seagate-ironwolf-pro-4096-3.5sata', 'Seagate', 'IronWolf Pro', '3.5 SATA', '4 TB', 'HDD Seagate IronWolf Pro 4 TB');
INSERT IGNORE INTO `pc_parts_picker`.hdd VALUES ('seagate-ironwolf-pro-16384-3.5sata', 'Seagate', 'IronWolf Pro', '3.5 SATA', '16 TB', 'HDD Seagate IronWolf Pro 16 TB');
INSERT IGNORE INTO `pc_parts_picker`.hdd VALUES ('wd-blue-4096-3.5sata', 'WD', 'Blue', '3.5 SATA', '4 TB', 'HDD WD Blue 4 TB');
INSERT IGNORE INTO `pc_parts_picker`.hdd VALUES ('seagate-barracuda-3072-3.5sata', 'Seagate', 'Barracuda', '3.5 SATA', '3 TB', 'HDD Seagate Barracuda 3 TB');
INSERT IGNORE INTO `pc_parts_picker`.hdd VALUES ('seagate-barracuda-compute-4096-3.5sata', 'Seagate', 'Barracuda Compute', '3.5 SATA', '4 TB', 'HDD Seagate Barracuda Compute 4 TB');
INSERT IGNORE INTO `pc_parts_picker`.hdd VALUES ('seagate-barracuda-compute-8192-3.5sata', 'Seagate', 'Barracuda Compute', '3.5 SATA', '8 TB', 'HDD Seagate Barracuda Compute 8 TB');
INSERT IGNORE INTO `pc_parts_picker`.hdd VALUES ('wd-black-series-2048-3.5sata', 'WD', 'BLACK SERIES', '3.5 SATA', '2 TB', 'HDD WD BLACK SERIES 2 TB');
INSERT IGNORE INTO `pc_parts_picker`.hdd VALUES ('seagate-barracuda-2048-3.5sata', 'Seagate', 'Barracuda', '3.5 SATA', '2 TB', 'HDD Seagate Barracuda 2 TB');
INSERT IGNORE INTO `pc_parts_picker`.hdd VALUES ('seagate-barracuda-500-3.5sata', 'Seagate', 'Barracuda', '3.5 SATA', '500 GB', 'HDD Seagate Barracuda 500 GB');
INSERT IGNORE INTO `pc_parts_picker`.hdd VALUES ('seagate-ironwolf-nas-8192-3.5sata', 'Seagate', 'IronWolf NAS', '3.5 SATA', '8 TB', 'HDD Seagate IronWolf NAS 8 TB');
INSERT IGNORE INTO `pc_parts_picker`.hdd VALUES ('wd-caviar-green-500-3.5sata', 'WD', 'Caviar Green', '3.5 SATA', '500 GB', 'HDD WD Caviar Green 500 GB');
INSERT IGNORE INTO `pc_parts_picker`.hdd VALUES ('seagate-barracuda-1024-3.5sata', 'Seagate', 'Barracuda', '3.5 SATA', '1 TB', 'HDD Seagate Barracuda 1 TB');
INSERT IGNORE INTO `pc_parts_picker`.hdd VALUES ('seagate-exos-enterprise-x18-18432-3.5sata', 'Seagate', 'EXOS Enterprise X18', '3.5 SATA', '18 TB', 'HDD Seagate EXOS Enterprise X18 18 TB');
INSERT IGNORE INTO `pc_parts_picker`.hdd VALUES ('seagate-firecuda-1024-2.5sata', 'Seagate', 'FireCuda', '2.5 SATA', '1 TB', 'HDD Seagate FireCuda 1 TB');
INSERT IGNORE INTO `pc_parts_picker`.hdd VALUES ('wd-black-6144-3.5sata', 'WD', 'Black', '3.5 SATA', '6 TB', 'HDD WD Black 6 TB');
INSERT IGNORE INTO `pc_parts_picker`.hdd VALUES ('wd-re4-1024-3.5sata', 'WD', 'RE4', '3.5 SATA', '1 TB', 'HDD WD RE4 1 TB');
INSERT IGNORE INTO `pc_parts_picker`.hdd VALUES ('wd-blue-1024-3.5sata', 'WD', 'Blue', '3.5 SATA', '1 TB', 'HDD WD Blue 1 TB');
INSERT IGNORE INTO `pc_parts_picker`.hdd VALUES ('seagate-exos-enterprise-16384-3.5sata', 'Seagate', 'EXOS Enterprise', '3.5 SATA', '16 TB', 'HDD Seagate EXOS Enterprise 16 TB');
INSERT IGNORE INTO `pc_parts_picker`.hdd VALUES ('wd-caviar-blue-500-3.5sata', 'WD', 'Caviar Blue', '3.5 SATA', '500 GB', 'HDD WD Caviar Blue 500 GB');
INSERT IGNORE INTO `pc_parts_picker`.hdd VALUES ('seagate-barracuda-pro-10240-3.5sata', 'Seagate', 'BarraCuda Pro', '3.5 SATA', '10 TB', 'HDD Seagate BarraCuda Pro 10 TB');
INSERT IGNORE INTO `pc_parts_picker`.hdd VALUES ('wd-red-4096-3.5sata', 'WD', 'Red', '3.5 SATA', '4 TB', 'HDD WD Red 4 TB');
INSERT IGNORE INTO `pc_parts_picker`.hdd VALUES ('wd-blue-3072-3.5sata', 'WD', 'Blue', '3.5 SATA', '3 TB', 'HDD WD Blue 3 TB');
INSERT IGNORE INTO `pc_parts_picker`.hdd VALUES ('seagate-ironwolf-pro-18432-3.5sata', 'Seagate', 'IronWolf Pro', '3.5 SATA', '18 TB', 'HDD Seagate IronWolf Pro 18 TB');
INSERT IGNORE INTO `pc_parts_picker`.hdd VALUES ('seagate-barracuda-1024-2.5sata', 'Seagate', 'BarraCuda', '2.5 SATA', '1 TB', 'HDD Seagate BarraCuda 1 TB');
INSERT IGNORE INTO `pc_parts_picker`.hdd VALUES ('seagate-ironwolf-nas-6144-3.5sata', 'Seagate', 'IronWolf NAS', '3.5 SATA', '6 TB', 'HDD Seagate IronWolf NAS 6 TB');
INSERT IGNORE INTO `pc_parts_picker`.hdd VALUES ('seagate-firecuda-2048-2.5sata', 'Seagate', 'FireCuda', '2.5 SATA', '2 TB', 'HDD Seagate FireCuda 2 TB');
INSERT IGNORE INTO `pc_parts_picker`.hdd VALUES ('seagate-superspeed-hdd-1024-2.5sata', 'Seagate', 'SuperSpeed HDD', '2.5 SATA', '1 TB', 'HDD Seagate SuperSpeed HDD 1 TB');
INSERT IGNORE INTO `pc_parts_picker`.hdd VALUES ('wd-black-1024-2.5sata', 'WD', 'Black', '2.5 SATA', '1 TB', 'HDD WD Black 1 TB');
INSERT IGNORE INTO `pc_parts_picker`.hdd VALUES ('seagate-barracuda-1024-3.5sata', 'Seagate', 'Barracuda', '3.5 SATA', '1 TB', 'HDD Seagate Barracuda 1 TB');
INSERT IGNORE INTO `pc_parts_picker`.hdd VALUES ('seagate-ironwolf-nas-4096-3.5sata', 'Seagate', 'IronWolf NAS', '3.5 SATA', '4 TB', 'HDD Seagate IronWolf NAS 4 TB');
INSERT IGNORE INTO `pc_parts_picker`.hdd VALUES ('seagate-barracuda-compute-3072-3.5sata', 'Seagate', 'Barracuda Compute', '3.5 SATA', '3 TB', 'HDD Seagate Barracuda Compute 3 TB');
INSERT IGNORE INTO `pc_parts_picker`.hdd VALUES ('wd-blue-2048-3.5sata', 'WD', 'Blue', '3.5 SATA', '2 TB', 'HDD WD Blue 2 TB');
INSERT IGNORE INTO `pc_parts_picker`.hdd VALUES ('wd-blue-6144-3.5sata', 'WD', 'Blue', '3.5 SATA', '6 TB', 'HDD WD Blue 6 TB');
INSERT IGNORE INTO `pc_parts_picker`.hdd VALUES ('wd-blue-500-3.5sata', 'WD', 'Blue', '3.5 SATA', '500 GB', 'HDD WD Blue 500 GB');
INSERT IGNORE INTO `pc_parts_picker`.hdd VALUES ('seagate-ironwolf-nas-10240-3.5sata', 'Seagate', 'IronWolf NAS', '3.5 SATA', '10 TB', 'HDD Seagate IronWolf NAS 10 TB');
INSERT IGNORE INTO `pc_parts_picker`.hdd VALUES ('wd-red-8192-3.5sata', 'WD', 'Red', '3.5 SATA', '8 TB', 'HDD WD Red 8 TB');
INSERT IGNORE INTO `pc_parts_picker`.hdd VALUES ('seagate-barracuda-2048-2.5sata', 'Seagate', 'BarraCuda', '2.5 SATA', '2 TB', 'HDD Seagate BarraCuda 2 TB');
INSERT IGNORE INTO `pc_parts_picker`.hdd VALUES ('seagate-exos-enterprise-14336-3.5sata', 'Seagate', 'EXOS Enterprise', '3.5 SATA', '14 TB', 'HDD Seagate EXOS Enterprise 14 TB');
INSERT IGNORE INTO `pc_parts_picker`.hdd VALUES ('seagate-st4000nc001-4096-3.5sata', 'Seagate', 'ST4000NC001', '3.5 SATA', '4 TB', 'HDD Seagate ST4000NC001 4 TB');
INSERT IGNORE INTO `pc_parts_picker`.hdd VALUES ('seagate-st500vm000-500-3.5sata', 'Seagate', 'ST500VM000', '3.5 SATA', '500 GB', 'HDD Seagate ST500VM000 500 GB');
INSERT IGNORE INTO `pc_parts_picker`.hdd VALUES ('wd-caviar-green-1024-3.5sata', 'WD', 'Caviar Green', '3.5 SATA', '1 TB', 'HDD WD Caviar Green 1 TB');
INSERT IGNORE INTO `pc_parts_picker`.hdd VALUES ('seagate-firecuda-compute-2048-2.5sata', 'Seagate', 'FireCuda Compute', '2.5 SATA', '2 TB', 'HDD Seagate FireCuda Compute 2 TB');
INSERT IGNORE INTO `pc_parts_picker`.hdd VALUES ('seagate-ironwolf-nas-8192-3.5sata', 'Seagate', 'IronWolf NAS', '3.5 SATA', '8 TB', 'HDD Seagate IronWolf NAS 8 TB');
INSERT IGNORE INTO `pc_parts_picker`.hdd VALUES ('seagate-barracuda-5120-2.5sata', 'Seagate', 'BarraCuda', '2.5 SATA', '5 TB', 'HDD Seagate BarraCuda 5 TB');
INSERT IGNORE INTO `pc_parts_picker`.hdd VALUES ('seagate-barracuda-6144-3.5sata', 'Seagate', 'Barracuda', '3.5 SATA', '6 TB', 'HDD Seagate Barracuda 6 TB');
INSERT IGNORE INTO `pc_parts_picker`.hdd VALUES ('seagate-barracuda-compute-1024-3.5sata', 'Seagate', 'Barracuda Compute', '3.5 SATA', '1 TB', 'HDD Seagate Barracuda Compute 1 TB');
INSERT IGNORE INTO `pc_parts_picker`.hdd VALUES ('seagate-firecuda-2048-3.5sata', 'Seagate', 'FireCuda', '3.5 SATA', '2 TB', 'HDD Seagate FireCuda 2 TB');
INSERT IGNORE INTO `pc_parts_picker`.hdd VALUES ('seagate-barracuda-pro-compute-1024-2.5sata', 'Seagate', 'BarraCuda Pro Compute', '2.5 SATA', '1 TB', 'HDD Seagate BarraCuda Pro Compute 1 TB');
INSERT IGNORE INTO `pc_parts_picker`.hdd VALUES ('wd-caviar-black-2048-3.5sata', 'WD', 'Caviar Black', '3.5 SATA', '2 TB', 'HDD WD Caviar Black 2 TB');
INSERT IGNORE INTO `pc_parts_picker`.hdd VALUES ('wd-red-4096-3.5sata', 'WD', 'Red', '3.5 SATA', '4 TB', 'HDD WD Red 4 TB');
INSERT IGNORE INTO `pc_parts_picker`.hdd VALUES ('seagate-ironwolf-pro-8192-3.5sata', 'Seagate', 'IronWolf Pro', '3.5 SATA', '8 TB', 'HDD Seagate IronWolf Pro 8 TB');
INSERT IGNORE INTO `pc_parts_picker`.hdd VALUES ('wd-blue-mobile-1024-2.5sata', 'WD', 'Blue Mobile', '2.5 SATA', '1 TB', 'HDD WD Blue Mobile 1 TB');
INSERT IGNORE INTO `pc_parts_picker`.hdd VALUES ('wd-red-10240-3.5sata', 'WD', 'Red', '3.5 SATA', '10 TB', 'HDD WD Red 10 TB');
INSERT IGNORE INTO `pc_parts_picker`.hdd VALUES ('wd-red-pro-4096-3.5sata', 'WD', 'Red Pro', '3.5 SATA', '4 TB', 'HDD WD Red Pro 4 TB');
INSERT IGNORE INTO `pc_parts_picker`.hdd VALUES ('wd-red-12288-3.5sata', 'WD', 'Red', '3.5 SATA', '12 TB', 'HDD WD Red 12 TB');
INSERT IGNORE INTO `pc_parts_picker`.hdd VALUES ('wd-red-2048-3.5sata', 'WD', 'Red', '3.5 SATA', '2 TB', 'HDD WD Red 2 TB');
INSERT IGNORE INTO `pc_parts_picker`.hdd VALUES ('wd-mainstream-1024-3.5sata', 'WD', 'Mainstream', '3.5 SATA', '1 TB', 'HDD WD Mainstream 1 TB');
INSERT IGNORE INTO `pc_parts_picker`.hdd VALUES ('seagate-ironwolf-nas-16384-3.5sata', 'Seagate', 'IronWolf NAS', '3.5 SATA', '16 TB', 'HDD Seagate IronWolf NAS 16 TB');
INSERT IGNORE INTO `pc_parts_picker`.hdd VALUES ('wd-red-14336-3.5sata', 'WD', 'Red', '3.5 SATA', '14 TB', 'HDD WD Red 14 TB');
INSERT IGNORE INTO `pc_parts_picker`.hdd VALUES ('seagate-barracuda-500-3.5sata', 'Seagate', 'BarraCuda', '3.5 SATA', '500 GB', 'HDD Seagate BarraCuda 500 GB');
INSERT IGNORE INTO `pc_parts_picker`.hdd VALUES ('seagate-nas-hdd-2048-3.5sata', 'Seagate', 'NAS HDD', '3.5 SATA', '2 TB', 'HDD Seagate NAS HDD 2 TB');
INSERT IGNORE INTO `pc_parts_picker`.hdd VALUES ('seagate-exos-x16-12288-3.5sata', 'Seagate', 'Exos X16', '3.5 SATA', '12 TB', 'HDD Seagate Exos X16 12 TB');
INSERT IGNORE INTO `pc_parts_picker`.hdd VALUES ('wd-red-6144-3.5sata', 'WD', 'Red', '3.5 SATA', '6 TB', 'HDD WD Red 6 TB');
INSERT IGNORE INTO `pc_parts_picker`.hdd VALUES ('wd-caviar-blue-500-3.5sata', 'WD', 'Caviar Blue', '3.5 SATA', '500 GB', 'HDD WD Caviar Blue 500 GB');
INSERT IGNORE INTO `pc_parts_picker`.hdd VALUES ('wd-black-series-4096-3.5sata', 'WD', 'BLACK SERIES', '3.5 SATA', '4 TB', 'HDD WD BLACK SERIES 4 TB');
INSERT IGNORE INTO `pc_parts_picker`.hdd VALUES ('seagate-barracuda-4096-2.5sata', 'Seagate', 'BarraCuda', '2.5 SATA', '4 TB', 'HDD Seagate BarraCuda 4 TB');
INSERT IGNORE INTO `pc_parts_picker`.hdd VALUES ('wd-gold-16384-3.5sata', 'WD', 'Gold', '3.5 SATA', '16 TB', 'HDD WD Gold 16 TB');
INSERT IGNORE INTO `pc_parts_picker`.hdd VALUES ('seagate-barracuda-pro-14336-3.5sata', 'Seagate', 'BarraCuda Pro', '3.5 SATA', '14 TB', 'HDD Seagate BarraCuda Pro 14 TB');
INSERT IGNORE INTO `pc_parts_picker`.hdd VALUES ('wd-caviar-black-1024-3.5sata', 'WD', 'Caviar Black', '3.5 SATA', '1 TB', 'HDD WD Caviar Black 1 TB');
INSERT IGNORE INTO `pc_parts_picker`.hdd VALUES ('wd-red-3072-3.5sata', 'WD', 'Red', '3.5 SATA', '3 TB', 'HDD WD Red 3 TB');
INSERT IGNORE INTO `pc_parts_picker`.hdd VALUES ('seagate-ironwolf-nas-2048-3.5sata', 'Seagate', 'IronWolf NAS', '3.5 SATA', '2 TB', 'HDD Seagate IronWolf NAS 2 TB');
INSERT IGNORE INTO `pc_parts_picker`.hdd VALUES ('seagate-exos-enterprise-4096-3.5sata', 'Seagate', 'EXOS Enterprise', '3.5 SATA', '4 TB', 'HDD Seagate EXOS Enterprise 4 TB');
INSERT IGNORE INTO `pc_parts_picker`.hdd VALUES ('seagate-st2000dx001-2048-3.5sata', 'Seagate', 'ST2000DX001', '3.5 SATA', '2 TB', 'HDD Seagate ST2000DX001 2 TB');
INSERT IGNORE INTO `pc_parts_picker`.hdd VALUES ('seagate-barracuda-pro-4096-3.5sata', 'Seagate', 'BarraCuda Pro', '3.5 SATA', '4 TB', 'HDD Seagate BarraCuda Pro 4 TB');
INSERT IGNORE INTO `pc_parts_picker`.hdd VALUES ('wd-wd-blue-500-2.5sata', 'WD', 'WD Blue', '2.5 SATA', '500 GB', 'HDD WD WD Blue 500 GB');
INSERT IGNORE INTO `pc_parts_picker`.hdd VALUES ('seagate-barracuda-compute-2048-3.5sata', 'Seagate', 'Barracuda Compute', '3.5 SATA', '2 TB', 'HDD Seagate Barracuda Compute 2 TB');
INSERT IGNORE INTO `pc_parts_picker`.hdd VALUES ('seagate-pipeline-hd-250-3.5sata', 'Seagate', 'Pipeline HD', '3.5 SATA', '250 GB', 'HDD Seagate Pipeline HD 250 GB');
INSERT IGNORE INTO `pc_parts_picker`.hdd VALUES ('wd-velociraptor-1024-3.5sata', 'WD', 'VelociRaptor', '3.5 SATA', '1 TB', 'HDD WD VelociRaptor 1 TB');
INSERT IGNORE INTO `pc_parts_picker`.hdd VALUES ('wd-purple-8192-3.5sata', 'WD', 'Purple', '3.5 SATA', '8 TB', 'HDD WD Purple 8 TB');
INSERT IGNORE INTO `pc_parts_picker`.hdd VALUES ('seagate-barracuda-compute-2048-2.5sata', 'Seagate', 'Barracuda Compute', '2.5 SATA', '2 TB', 'HDD Seagate Barracuda Compute 2 TB');
INSERT IGNORE INTO `pc_parts_picker`.hdd VALUES ('seagate-ironwolf-pro-10240-3.5sata', 'Seagate', 'IronWolf Pro', '3.5 SATA', '10 TB', 'HDD Seagate IronWolf Pro 10 TB');
INSERT IGNORE INTO `pc_parts_picker`.hdd VALUES ('seagate-surveillance-hdd-1024-3.5sata', 'Seagate', 'Surveillance HDD', '3.5 SATA', '1 TB', 'HDD Seagate Surveillance HDD 1 TB');
INSERT IGNORE INTO `pc_parts_picker`.hdd VALUES ('seagate-barracuda-2048-3.5sata', 'Seagate', 'Barracuda', '3.5 SATA', '2 TB', 'HDD Seagate Barracuda 2 TB');
INSERT IGNORE INTO `pc_parts_picker`.hdd VALUES ('seagate-st500lm021-500-2.5sata', 'Seagate', 'ST500LM021', '2.5 SATA', '500 GB', 'HDD Seagate ST500LM021 500 GB');
INSERT IGNORE INTO `pc_parts_picker`.hdd VALUES ('wd-gold-10240-3.5sata', 'WD', 'Gold', '3.5 SATA', '10 TB', 'HDD WD Gold 10 TB');
INSERT IGNORE INTO `pc_parts_picker`.hdd VALUES ('wd-caviar-green-500-3.5sata', 'WD', 'Caviar Green', '3.5 SATA', '500 GB', 'HDD WD Caviar Green 500 GB');
INSERT IGNORE INTO `pc_parts_picker`.hdd VALUES ('wd-caviar-blue-320-3.5pata', 'WD', 'Caviar Blue', '3.5 PATA', '320 GB', 'HDD WD Caviar Blue 320 GB');
INSERT IGNORE INTO `pc_parts_picker`.hdd VALUES ('wd-gold-4096-3.5sata', 'WD', 'Gold', '3.5 SATA', '4 TB', 'HDD WD Gold 4 TB');
INSERT IGNORE INTO `pc_parts_picker`.hdd VALUES ('wd-caviar-blue-250-3.5sata', 'WD', 'Caviar Blue', '3.5 SATA', '250 GB', 'HDD WD Caviar Blue 250 GB');
INSERT IGNORE INTO `pc_parts_picker`.hdd VALUES ('wd-wdbh2d0020hnc-nrsn-2048-3.5sata', 'WD', 'WDBH2D0020HNC-NRSN', '3.5 SATA', '2 TB', 'HDD WD WDBH2D0020HNC-NRSN 2 TB');
