INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('msi-b450-tomahawk-max', 'MSI', '', 'B450', 'AM4', 'ATX', 'MSI B450 TOMAHAWK MAX');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('msi-mag-b550-tomahawk', 'MSI', '', 'B550', 'AM4', 'ATX', 'MSI MAG B550 TOMAHAWK');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('msi-z390-a-pro', 'MSI', '', 'Z390', 'LGA1151', 'ATX', 'MSI Z390-A PRO');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('msi-b550-a-pro', 'MSI', '', 'B550', 'AM4', 'ATX', 'MSI B550-A PRO');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('msi-mag-x570-tomahawk-wifi', 'MSI', '', 'X570', 'AM4', 'ATX', 'MSI MAG X570 TOMAHAWK WIFI');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('msi-b450-gaming-plus-max', 'MSI', '', 'B450', 'AM4', 'ATX', 'MSI B450 Gaming Plus MAX');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('msi-mpg-z490-gaming-plus', 'MSI', '', 'Z490', 'LGA1200', 'ATX', 'MSI MPG Z490 GAMING PLUS');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('msi-mpg-b550-gaming-plus', 'MSI', '', 'B550', 'AM4', 'ATX', 'MSI MPG B550 GAMING PLUS');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('msi-b550m-pro-vdh-wifi', 'MSI', '', 'B550', 'AM4', 'Micro ATX', 'MSI B550M PRO-VDH WIFI');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('msi-b365m-pro-vdh', 'MSI', '', 'B365', 'LGA1151', 'Micro ATX', 'MSI B365M PRO-VDH');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('msi-mpg-z490-gaming-edge-wifi', 'MSI', '', 'Z490', 'LGA1200', 'ATX', 'MSI MPG Z490 GAMING EDGE WIFI');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('msi-mpg-x570-gaming-edge-wifi', 'MSI', '', 'X570', 'AM4', 'ATX', 'MSI MPG X570 GAMING EDGE WIFI');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('msi-b450-a-pro-max', 'MSI', '', 'B450', 'AM4', 'ATX', 'MSI B450-A PRO MAX');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('msi-mpg-b550-gaming-edge-wifi', 'MSI', '', 'B550', 'AM4', 'ATX', 'MSI MPG B550 GAMING EDGE WIFI');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('msi-mpg-z390-gaming-edge-ac', 'MSI', '', 'Z390', 'LGA1151', 'ATX', 'MSI MPG Z390 GAMING EDGE AC');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('msi-z490-a-pro', 'MSI', '', 'Z490', 'LGA1200', 'ATX', 'MSI Z490-A PRO');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('msi-b450m-bazooka-max-wifi', 'MSI', '', 'B450', 'AM4', 'Micro ATX', 'MSI B450M BAZOOKA MAX WIFI');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('msi-mpg-x570-gaming-plus', 'MSI', '', 'X570', 'AM4', 'ATX', 'MSI MPG X570 GAMING PLUS');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('msi-mag-b550m-mortar-wifi', 'MSI', '', 'B550', 'AM4', 'Micro ATX', 'MSI MAG B550M MORTAR WIFI');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('msi-b450-gaming-pro-carbon-max-wifi', 'MSI', '', 'B450', 'AM4', 'ATX', 'MSI B450 GAMING PRO CARBON MAX WIFI');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('msi-b460m-a-pro', 'MSI', '', 'B460', 'LGA1200', 'Micro ATX', 'MSI B460M-A PRO');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('msi-meg-x570-unify', 'MSI', '', 'X570', 'AM4', 'ATX', 'MSI MEG X570 UNIFY');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('msi-mpg-x570-gaming-pro-carbon-wifi', 'MSI', '', 'X570', 'AM4', 'ATX', 'MSI MPG X570 GAMING PRO CARBON WIFI');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('msi-b450m-pro-m2-max', 'MSI', '', 'B450', 'AM4', 'Micro ATX', 'MSI B450M PRO-M2 MAX');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('msi-b450i-gaming-plus-ac', 'MSI', '', 'B450', 'AM4', 'Mini ITX', 'MSI B450I GAMING PLUS AC');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('msi-h410m-a-pro', 'MSI', '', 'H410', 'LGA1200', 'Micro ATX', 'MSI H410M-A PRO');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('msi-x470-gaming-plus-max', 'MSI', '', 'X470', 'AM4', 'ATX', 'MSI X470 GAMING PLUS MAX');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('asus-tuf-b450m-plus-gaming', 'Asus', '', 'B450M', 'AM4', 'Micro ATX', 'Asus TUF B450M-PLUS GAMING');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('asus-prime-h310m-e-r2.0', 'Asus', '', 'H310M', 'LGA1151', 'Micro ATX', 'Asus PRIME H310M-E R2.0');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('msi-mpg-b550-gaming-carbon-wifi', 'MSI', '', 'B550', 'AM4', 'ATX', 'MSI MPG B550 GAMING CARBON WIFI');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('msi-mpg-z390-gaming-plus', 'MSI', '', 'Z390', 'LGA1151', 'ATX', 'MSI MPG Z390 GAMING PLUS');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('msi-a320m-a-pro-max', 'MSI', '', 'A320', 'AM4', 'Micro ATX', 'MSI A320M-A PRO MAX');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('msi-b450m-pro-vdh-max', 'MSI', '', 'B450', 'AM4', 'Micro ATX', 'MSI B450M PRO-VDH MAX');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('msi-mag-z490-tomahawk', 'MSI', '', 'Z490', 'LGA1200', 'ATX', 'MSI MAG Z490 TOMAHAWK');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('asus-tuf-gaming-b550m-plus-(wi-fi)', 'Asus', '', 'B550M', 'AM4', 'Micro ATX', 'Asus TUF GAMING B550M-PLUS (WI-FI)');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('msi-meg-x570-unify', 'MSI', '', 'X570', 'AM4', 'ATX', 'MSI MEG X570 UNIFY');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('msi-mag-x570-tomahawk-wifi', 'MSI', '', 'X570', 'AM4', 'ATX', 'MSI MAG X570 TOMAHAWK WIFI');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('msi-b450-gaming-pro-carbon-ac', 'MSI', '', 'B450', 'AM4', 'ATX', 'MSI B450 GAMING PRO CARBON AC');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('msi-z170a-gaming-m7', 'MSI', '', 'Z170', 'LGA1151', 'ATX', 'MSI Z170A GAMING M7');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('msi-z170a-krait-gaming-3x', 'MSI', '', 'Z170', 'LGA1151', 'ATX', 'MSI Z170A KRAIT GAMING 3X');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('msi-b450-tomahawk-max', 'MSI', '', 'B450', 'AM4', 'ATX', 'MSI B450 TOMAHAWK MAX');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('msi-z77-mpower', 'MSI', '', 'Z77 ', 'LGA1155', 'ATX', 'MSI Z77 MPOWER');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('msi-b450-tomahawk', 'MSI', '', 'B450', 'AM4', 'ATX', 'MSI B450 TOMAHAWK');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('msi-z87m-gaming', 'MSI', '', 'Z87M', 'LGA1150', 'Micro ATX', 'MSI Z87M GAMING');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('msi-b450-gaming-plus-max', 'MSI', '', 'B450', 'AM4', 'ATX', 'MSI B450 Gaming Plus MAX');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('msi-b450m-mortar-max', 'MSI', '', 'B450', 'AM4', 'Micro ATX', 'MSI B450M MORTAR MAX');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('msi-mpg-z390-gaming-edge-ac', 'MSI', '', 'Z390', 'LGA1151', 'ATX', 'MSI MPG Z390 GAMING EDGE AC');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('msi-z170a-gaming-m5', 'MSI', '', 'Z170', 'LGA1151', 'ATX', 'MSI Z170A GAMING M5');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('msi-mpg-b550-gaming-plus', 'MSI', '', 'B550', 'AM4', 'ATX', 'MSI MPG B550 GAMING PLUS');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('msi-b550m-pro-vdh-wifi', 'MSI', '', 'B550', 'AM4', 'Micro ATX', 'MSI B550M PRO-VDH WIFI');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('msi-mag-b550m-mortar-wifi', 'MSI', '', 'B550', 'AM4', 'Micro ATX', 'MSI MAG B550M MORTAR WIFI');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('msi-b450m-mortar', 'MSI', '', 'B450', 'AM4', 'Micro ATX', 'MSI B450M MORTAR');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('msi-b250m-mortar', 'MSI', '', 'B250', 'LGA1151', 'Micro ATX', 'MSI B250M MORTAR');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('msi-b250m-gaming-pro', 'MSI', '', 'B250', 'LGA1151', 'Micro ATX', 'MSI B250M GAMING PRO');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('msi-mag-b550-tomahawk', 'MSI', '', 'B550', 'AM4', 'ATX', 'MSI MAG B550 TOMAHAWK');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('msi-z97-mpower', 'MSI', '', 'Z97 ', 'LGA1150', 'ATX', 'MSI Z97 MPOWER');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('msi-b450m-gaming-plus', 'MSI', '', 'B450', 'AM4', 'Micro ATX', 'MSI B450M GAMING PLUS');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('msi-a88x-g45-gaming', 'MSI', '', 'A88X', 'FM2+', 'ATX', 'MSI A88X-G45 GAMING');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('msi-z270-gaming-pro-carbon', 'MSI', '', 'Z270', 'LGA1151', 'ATX', 'MSI Z270 GAMING PRO CARBON');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('msi-mag-z390-tomahawk', 'MSI', '', 'Z390', 'LGA1151', 'ATX', 'MSI MAG Z390 TOMAHAWK');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('msi-b450-a-pro-max', 'MSI', '', 'B450', 'AM4', 'ATX', 'MSI B450-A PRO MAX');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('msi-z97s-sli-krait-edition', 'MSI', '', 'Z97S', 'LGA1150', 'ATX', 'MSI Z97S SLI Krait Edition');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('msi-mpg-z490-gaming-plus', 'MSI', '', 'Z490', 'LGA1200', 'ATX', 'MSI MPG Z490 GAMING PLUS');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('msi-meg-z390-godlike', 'MSI', '', 'Z390', 'LGA1151', 'EATX', 'MSI MEG Z390 GODLIKE');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('msi-z270-tomahawk-arctic', 'MSI', '', 'Z270', 'LGA1151', 'ATX', 'MSI Z270 TOMAHAWK ARCTIC');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('msi-b250m-mortar-arctic', 'MSI', '', 'B250', 'LGA1151', 'Micro ATX', 'MSI B250M MORTAR ARCTIC');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('msi-b350-pc-mate', 'MSI', '', 'B350', 'AM4', 'ATX', 'MSI B350 PC MATE');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('msi-z97m-gaming', 'MSI', '', 'Z97M', 'LGA1150', 'Micro ATX', 'MSI Z97M Gaming');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('msi-b550-a-pro', 'MSI', '', 'B550', 'AM4', 'ATX', 'MSI B550-A PRO');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('msi-mpg-z390-gaming-pro-carbon', 'MSI', '', 'Z390', 'LGA1151', 'ATX', 'MSI MPG Z390 GAMING PRO CARBON');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('msi-z170-a-pro', 'MSI', '', 'Z170', 'LGA1151', 'ATX', 'MSI Z170-A PRO');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('msi-z170a-gaming-pro-carbon', 'MSI', '', 'Z170', 'LGA1151', 'ATX', 'MSI Z170A GAMING PRO CARBON');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('msi-z270-gaming-m7', 'MSI', '', 'Z270', 'LGA1151', 'ATX', 'MSI Z270 GAMING M7');
