INSERT IGNORE INTO `pc_parts_picker`.psu VALUES ('evga-bq-600-bronze', 'EVGA', 'BQ', 'ATX', '600', 'bronze', 'EVGA BQ 600W');
INSERT IGNORE INTO `pc_parts_picker`.psu VALUES ('evga-bq-500-bronze', 'EVGA', 'BQ', 'ATX', '500', 'bronze', 'EVGA BQ 500W');
INSERT IGNORE INTO `pc_parts_picker`.psu VALUES ('cm-mwe-gold-650-gold', 'Cooler Master', 'MWE Gold', 'ATX', '650', 'gold', 'Cooler Master MWE Gold 650W');
INSERT IGNORE INTO `pc_parts_picker`.psu VALUES ('evga-br-500-bronze', 'EVGA', 'BR', 'ATX', '500', 'bronze', 'EVGA BR 500W');
INSERT IGNORE INTO `pc_parts_picker`.psu VALUES ('corsair-cxm-650-bronze', 'Corsair', 'CXM', 'ATX', '650', 'bronze', 'Corsair CXM 650W');
INSERT IGNORE INTO `pc_parts_picker`.psu VALUES ('corsair-cxm-550-bronze', 'Corsair', 'CXM', 'ATX', '550', 'bronze', 'Corsair CXM 550W');
INSERT IGNORE INTO `pc_parts_picker`.psu VALUES ('evga-br-450-bronze', 'EVGA', 'BR', 'ATX', '450', 'bronze', 'EVGA BR 450W');
INSERT IGNORE INTO `pc_parts_picker`.psu VALUES ('corsair-axi-1600-titanium', 'Corsair', 'AXi', 'ATX', '1600', 'titanium', 'Corsair AXi 1600W');
INSERT IGNORE INTO `pc_parts_picker`.psu VALUES ('corsair-txm-gold-650-gold', 'Corsair', 'TXM Gold', 'ATX', '650', 'gold', 'Corsair TXM Gold 650W');
INSERT IGNORE INTO `pc_parts_picker`.psu VALUES ('evga-br-700-bronze', 'EVGA', 'BR', 'ATX', '700', 'bronze', 'EVGA BR 700W');
INSERT IGNORE INTO `pc_parts_picker`.psu VALUES ('corsair-txm-gold-550-gold', 'Corsair', 'TXM Gold', 'ATX', '550', 'gold', 'Corsair TXM Gold 550W');
INSERT IGNORE INTO `pc_parts_picker`.psu VALUES ('corsair-cv-550-bronze', 'Corsair', 'CV', 'ATX', '550', 'bronze', 'Corsair CV 550W');
INSERT IGNORE INTO `pc_parts_picker`.psu VALUES ('evga-g3-750-gold', 'EVGA', 'G3', 'ATX', '750', 'gold', 'EVGA G3 750W');
INSERT IGNORE INTO `pc_parts_picker`.psu VALUES ('evga-b5-650-bronze', 'EVGA', 'B5', 'ATX', '650', 'bronze', 'EVGA B5 650W');
INSERT IGNORE INTO `pc_parts_picker`.psu VALUES ('cm-mwe-gold-750-gold', 'Cooler Master', 'MWE Gold', 'ATX', '750', 'gold', 'Cooler Master MWE Gold 750W');
INSERT IGNORE INTO `pc_parts_picker`.psu VALUES ('corsair-cv-450-bronze', 'Corsair', 'CV', 'ATX', '450', 'bronze', 'Corsair CV 450W');
INSERT IGNORE INTO `pc_parts_picker`.psu VALUES ('corsair-cv-650-bronze', 'Corsair', 'CV', 'ATX', '650', 'bronze', 'Corsair CV 650W');
INSERT IGNORE INTO `pc_parts_picker`.psu VALUES ('corsair-hx-platinum-1000-platinum', 'Corsair', 'HX Platinum', 'ATX', '1000', 'platinum', 'Corsair HX Platinum 1000W');
INSERT IGNORE INTO `pc_parts_picker`.psu VALUES ('corsair-rmx-1000-gold', 'Corsair', 'RMx', 'ATX', '1000', 'gold', 'Corsair RMx 1000W');
INSERT IGNORE INTO `pc_parts_picker`.psu VALUES ('corsair-sf-750-platinum', 'Corsair', 'SF', 'SFX', '750', 'platinum', 'Corsair SF 750W');
INSERT IGNORE INTO `pc_parts_picker`.psu VALUES ('evga-br-600-bronze', 'EVGA', 'BR', 'ATX', '600', 'bronze', 'EVGA BR 600W');
INSERT IGNORE INTO `pc_parts_picker`.psu VALUES ('evga-bq-750-bronze', 'EVGA', 'BQ', 'ATX', '750', 'bronze', 'EVGA BQ 750W');
INSERT IGNORE INTO `pc_parts_picker`.psu VALUES ('evga-supernova-ga-850-gold', 'EVGA', 'SuperNOVA GA', 'ATX', '850', 'gold', 'EVGA SuperNOVA GA 850W');
INSERT IGNORE INTO `pc_parts_picker`.psu VALUES ('corsair-cxm-750-bronze', 'Corsair', 'CXM', 'ATX', '750', 'bronze', 'Corsair CXM 750W');
INSERT IGNORE INTO `pc_parts_picker`.psu VALUES ('evga-100-w1-0500-kr-500-none', 'EVGA', '100-W1-0500-KR', 'ATX', '500', 'none', 'EVGA 100-W1-0500-KR 500W');
INSERT IGNORE INTO `pc_parts_picker`.psu VALUES ('corsair-hx-platinum-1200-platinum', 'Corsair', 'HX Platinum', 'ATX', '1200', 'platinum', 'Corsair HX Platinum 1200W');
INSERT IGNORE INTO `pc_parts_picker`.psu VALUES ('evga-100-n1-0400-l1-400-none', 'EVGA', '100-N1-0400-L1', 'ATX', '400', 'none', 'EVGA 100-N1-0400-L1 400W');
INSERT IGNORE INTO `pc_parts_picker`.psu VALUES ('cm-mwe-gold-550-gold', 'Cooler Master', 'MWE Gold', 'ATX', '550', 'gold', 'Cooler Master MWE Gold 550W');
INSERT IGNORE INTO `pc_parts_picker`.psu VALUES ('corsair-txm-gold-750-gold', 'Corsair', 'TXM Gold', 'ATX', '750', 'gold', 'Corsair TXM Gold 750W');
INSERT IGNORE INTO `pc_parts_picker`.psu VALUES ('evga-g3-650-gold', 'EVGA', 'G3', 'ATX', '650', 'gold', 'EVGA G3 650W');
INSERT IGNORE INTO `pc_parts_picker`.psu VALUES ('evga-g1+-1000-gold', 'EVGA', 'G1+', 'ATX', '1000', 'gold', 'EVGA G1+ 1000W');
INSERT IGNORE INTO `pc_parts_picker`.psu VALUES ('evga-g3-850-gold', 'EVGA', 'G3', 'ATX', '850', 'gold', 'EVGA G3 850W');
INSERT IGNORE INTO `pc_parts_picker`.psu VALUES ('evga-supernova-ga-750-gold', 'EVGA', 'SuperNOVA GA', 'ATX', '750', 'gold', 'EVGA SuperNOVA GA 750W');
INSERT IGNORE INTO `pc_parts_picker`.psu VALUES ('evga-supernova-ga-650-gold', 'EVGA', 'SuperNOVA GA', 'ATX', '650', 'gold', 'EVGA SuperNOVA GA 650W');
INSERT IGNORE INTO `pc_parts_picker`.psu VALUES ('cm-masterwatt-650-bronze', 'Cooler Master', 'MasterWatt', 'ATX', '650', 'bronze', 'Cooler Master MasterWatt 650W');
INSERT IGNORE INTO `pc_parts_picker`.psu VALUES ('evga-b5-550-bronze', 'EVGA', 'B5', 'ATX', '550', 'bronze', 'EVGA B5 550W');
INSERT IGNORE INTO `pc_parts_picker`.psu VALUES ('corsair-sf-600-platinum', 'Corsair', 'SF', 'SFX', '600', 'platinum', 'Corsair SF 600W');
INSERT IGNORE INTO `pc_parts_picker`.psu VALUES ('corsair-axi-1200-platinum', 'Corsair', 'AXi', 'ATX', '1200', 'platinum', 'Corsair AXi 1200W');
INSERT IGNORE INTO `pc_parts_picker`.psu VALUES ('cm-masterwatt-750-bronze', 'Cooler Master', 'MasterWatt', 'ATX', '750', 'bronze', 'Cooler Master MasterWatt 750W');
INSERT IGNORE INTO `pc_parts_picker`.psu VALUES ('corsair-sf-600-gold', 'Corsair', 'SF', 'SFX', '600', 'gold', 'Corsair SF 600W');
INSERT IGNORE INTO `pc_parts_picker`.psu VALUES ('evga-100-w1-0600-k1-600-none', 'EVGA', '100-W1-0600-K1', 'ATX', '600', 'none', 'EVGA 100-W1-0600-K1 600W');
INSERT IGNORE INTO `pc_parts_picker`.psu VALUES ('corsair-cxf-650-bronze', 'Corsair', 'CXF', 'ATX', '650', 'bronze', 'Corsair CXF 650W');
INSERT IGNORE INTO `pc_parts_picker`.psu VALUES ('evga-bq-650-bronze', 'EVGA', 'BQ', 'ATX', '650', 'bronze', 'EVGA BQ 650W');
INSERT IGNORE INTO `pc_parts_picker`.psu VALUES ('evga-supernova-gm-550-gold', 'EVGA', 'SuperNOVA GM', 'SFX', '550', 'gold', 'EVGA SuperNOVA GM 550W');
INSERT IGNORE INTO `pc_parts_picker`.psu VALUES ('corsair-cxf-650-bronze', 'Corsair', 'CXF', 'ATX', '650', 'bronze', 'Corsair CXF 650W');
INSERT IGNORE INTO `pc_parts_picker`.psu VALUES ('silverstone-sfx-800-titanium', 'Silverstone', 'SFX', 'SFX', '800', 'titanium', 'Silverstone SFX 800W');
INSERT IGNORE INTO `pc_parts_picker`.psu VALUES ('evga-supernova-gm-650-gold', 'EVGA', 'SuperNOVA GM', 'SFX', '650', 'gold', 'EVGA SuperNOVA GM 650W');
INSERT IGNORE INTO `pc_parts_picker`.psu VALUES ('evga-g3-1000-gold', 'EVGA', 'G3', 'ATX', '1000', 'gold', 'EVGA G3 1000W');
INSERT IGNORE INTO `pc_parts_picker`.psu VALUES ('evga-supernova-gm-450-gold', 'EVGA', 'SuperNOVA GM', 'SFX', '450', 'gold', 'EVGA SuperNOVA GM 450W');
INSERT IGNORE INTO `pc_parts_picker`.psu VALUES ('corsair-hxi-1000-platinum', 'Corsair', 'HXi', 'ATX', '1000', 'platinum', 'Corsair HXi 1000W');
INSERT IGNORE INTO `pc_parts_picker`.psu VALUES ('evga-210-gq-0750-v1-750-gold', 'EVGA', '210-GQ-0750-V1', 'ATX', '750', 'gold', 'EVGA 210-GQ-0750-V1 750W');
INSERT IGNORE INTO `pc_parts_picker`.psu VALUES ('evga-w3-450-none', 'EVGA', 'W3', 'ATX', '450', 'none', 'EVGA W3 450W');
INSERT IGNORE INTO `pc_parts_picker`.psu VALUES ('evga-ba-600-bronze', 'EVGA', 'BA', 'ATX', '600', 'bronze', 'EVGA BA 600W');
INSERT IGNORE INTO `pc_parts_picker`.psu VALUES ('corsair-ax-1000-titanium', 'Corsair', 'AX', 'ATX', '1000', 'titanium', 'Corsair AX 1000W');
INSERT IGNORE INTO `pc_parts_picker`.psu VALUES ('corsair-cxf-750-bronze', 'Corsair', 'CXF', 'ATX', '750', 'bronze', 'Corsair CXF 750W');
INSERT IGNORE INTO `pc_parts_picker`.psu VALUES ('corsair-hx-platinum-750-platinum', 'Corsair', 'HX Platinum', 'ATX', '750', 'platinum', 'Corsair HX Platinum 750W');
INSERT IGNORE INTO `pc_parts_picker`.psu VALUES ('evga-210-gq-0650-v1-650-gold', 'EVGA', '210-GQ-0650-V1', 'ATX', '650', 'gold', 'EVGA 210-GQ-0650-V1 650W');
INSERT IGNORE INTO `pc_parts_picker`.psu VALUES ('evga-g3-550-gold', 'EVGA', 'G3', 'ATX', '550', 'gold', 'EVGA G3 550W');
INSERT IGNORE INTO `pc_parts_picker`.psu VALUES ('cm-mwe-bronze-v2-550-bronze', 'Cooler Master', 'MWE Bronze V2', 'ATX', '550', 'bronze', 'Cooler Master MWE Bronze V2 550W');
INSERT IGNORE INTO `pc_parts_picker`.psu VALUES ('evga-g5-650-gold', 'EVGA', 'G5', 'ATX', '650', 'gold', 'EVGA G5 650W');
INSERT IGNORE INTO `pc_parts_picker`.psu VALUES ('corsair-hx-platinum-850-platinum', 'Corsair', 'HX Platinum', 'ATX', '850', 'platinum', 'Corsair HX Platinum 850W');
INSERT IGNORE INTO `pc_parts_picker`.psu VALUES ('evga-t2-1600-titanium', 'EVGA', 'T2', 'ATX', '1600', 'titanium', 'EVGA T2 1600W');
INSERT IGNORE INTO `pc_parts_picker`.psu VALUES ('evga-p2-850-platinum', 'EVGA', 'P2', 'ATX', '850', 'platinum', 'EVGA P2 850W');
INSERT IGNORE INTO `pc_parts_picker`.psu VALUES ('cm-elite-v3-600-none', 'Cooler Master', 'Elite V3', 'ATX', '600', 'none', 'Cooler Master Elite V3 600W');
INSERT IGNORE INTO `pc_parts_picker`.psu VALUES ('evga-ba-500-bronze', 'EVGA', 'BA', 'ATX', '500', 'bronze', 'EVGA BA 500W');
INSERT IGNORE INTO `pc_parts_picker`.psu VALUES ('corsair-vs-650-none', 'Corsair', 'VS', 'ATX', '650', 'none', 'Corsair VS 650W');
INSERT IGNORE INTO `pc_parts_picker`.psu VALUES ('corsair-hxi-850-platinum', 'Corsair', 'HXi', 'ATX', '850', 'platinum', 'Corsair HXi 850W');
INSERT IGNORE INTO `pc_parts_picker`.psu VALUES ('evga-b5-750-bronze', 'EVGA', 'B5', 'ATX', '750', 'bronze', 'EVGA B5 750W');
INSERT IGNORE INTO `pc_parts_picker`.psu VALUES ('corsair-sf-450-gold', 'Corsair', 'SF', 'SFX', '450', 'gold', 'Corsair SF 450W');
INSERT IGNORE INTO `pc_parts_picker`.psu VALUES ('evga-g1+-750-gold', 'EVGA', 'G1+', 'ATX', '750', 'gold', 'EVGA G1+ 750W');
INSERT IGNORE INTO `pc_parts_picker`.psu VALUES ('cm-masterwatt-550-bronze', 'Cooler Master', 'MasterWatt', 'ATX', '550', 'bronze', 'Cooler Master MasterWatt 550W');
INSERT IGNORE INTO `pc_parts_picker`.psu VALUES ('evga-t2-1000-titanium', 'EVGA', 'T2', 'ATX', '1000', 'titanium', 'EVGA T2 1000W');
INSERT IGNORE INTO `pc_parts_picker`.psu VALUES ('corsair-ax-850-titanium', 'Corsair', 'AX', 'ATX', '850', 'titanium', 'Corsair AX 850W');
INSERT IGNORE INTO `pc_parts_picker`.psu VALUES ('cm-elite-v3-400-none', 'Cooler Master', 'Elite V3', 'ATX', '400', 'none', 'Cooler Master Elite V3 400W');
INSERT IGNORE INTO `pc_parts_picker`.psu VALUES ('evga-g5-750-gold', 'EVGA', 'G5', 'ATX', '750', 'gold', 'EVGA G5 750W');
INSERT IGNORE INTO `pc_parts_picker`.psu VALUES ('evga-p2-1600-platinum', 'EVGA', 'P2', 'ATX', '1600', 'platinum', 'EVGA P2 1600W');
INSERT IGNORE INTO `pc_parts_picker`.psu VALUES ('silverstone-sx700-pt-700-platinum', 'Silverstone', 'SX700-PT', 'SFX', '700', 'platinum', 'Silverstone SX700-PT 700W');
INSERT IGNORE INTO `pc_parts_picker`.psu VALUES ('cm-elite-v3-500-none', 'Cooler Master', 'Elite V3', 'ATX', '500', 'none', 'Cooler Master Elite V3 500W');
INSERT IGNORE INTO `pc_parts_picker`.psu VALUES ('corsair-rmx-750-gold', 'Corsair', 'RMx', 'ATX', '750', 'gold', 'Corsair RMx 750W');
INSERT IGNORE INTO `pc_parts_picker`.psu VALUES ('evga-100-n1-0750-l1-750-none', 'EVGA', '100-N1-0750-L1', 'ATX', '750', 'none', 'EVGA 100-N1-0750-L1 750W');
INSERT IGNORE INTO `pc_parts_picker`.psu VALUES ('evga-bq-850-bronze', 'EVGA', 'BQ', 'ATX', '850', 'bronze', 'EVGA BQ 850W');
INSERT IGNORE INTO `pc_parts_picker`.psu VALUES ('cm-mwe-bronze-v2-650-bronze', 'Cooler Master', 'MWE Bronze V2', 'ATX', '650', 'bronze', 'Cooler Master MWE Bronze V2 650W');
INSERT IGNORE INTO `pc_parts_picker`.psu VALUES ('cm-v-sfx-gold-850-gold', 'Cooler Master', 'V SFX Gold', 'SFX', '850', 'gold', 'Cooler Master V SFX Gold 850W');
