INSERT IGNORE INTO `pc_parts_picker`.ssd VALUES ('wd-blue-500-m2-sata', 'WD', 'Blue', 'M2 SATA', '500 GB', 'SSD WD Blue 500 GB');
INSERT IGNORE INTO `pc_parts_picker`.ssd VALUES ('wd-blue-sn550-1024-m2-nvme', 'WD', 'Blue SN550', 'M2 NVMe', '1 TB', 'SSD WD Blue SN550 1 TB');
INSERT IGNORE INTO `pc_parts_picker`.ssd VALUES ('wd-blue-sn550-500-m2-nvme', 'WD', 'Blue SN550', 'M2 NVMe', '500 GB', 'SSD WD Blue SN550 500 GB');
INSERT IGNORE INTO `pc_parts_picker`.ssd VALUES ('wd-blue-1024-m2-sata', 'WD', 'Blue', 'M2 SATA', '1 TB', 'SSD WD Blue 1 TB');
INSERT IGNORE INTO `pc_parts_picker`.ssd VALUES ('wd-sn750-1024-m2-nvme', 'WD', 'SN750', 'M2 NVMe', '1 TB', 'SSD WD SN750 1 TB');
INSERT IGNORE INTO `pc_parts_picker`.ssd VALUES ('wd-sn750-500-m2-nvme', 'WD', 'SN750', 'M2 NVMe', '500 GB', 'SSD WD SN750 500 GB');
INSERT IGNORE INTO `pc_parts_picker`.ssd VALUES ('wd-blue-500-m2-sata', 'WD', 'Blue', 'M2 SATA', '500 GB', 'SSD WD Blue 500 GB');
INSERT IGNORE INTO `pc_parts_picker`.ssd VALUES ('wd-blue-1024-m2-sata', 'WD', 'Blue', 'M2 SATA', '1 TB', 'SSD WD Blue 1 TB');
INSERT IGNORE INTO `pc_parts_picker`.ssd VALUES ('wd-blue-2048-m2-sata', 'WD', 'Blue', 'M2 SATA', '2 TB', 'SSD WD Blue 2 TB');
INSERT IGNORE INTO `pc_parts_picker`.ssd VALUES ('wd-green-1024-m2-sata', 'WD', 'Green', 'M2 SATA', '1 TB', 'SSD WD Green 1 TB');
INSERT IGNORE INTO `pc_parts_picker`.ssd VALUES ('wd-blue-250-m2-sata', 'WD', 'Blue', 'M2 SATA', '250 GB', 'SSD WD Blue 250 GB');
INSERT IGNORE INTO `pc_parts_picker`.ssd VALUES ('wd-green-240-m2-sata', 'WD', 'Green', 'M2 SATA', '240 GB', 'SSD WD Green 240 GB');
INSERT IGNORE INTO `pc_parts_picker`.ssd VALUES ('wd-wd-blue-2048-m2-sata', 'WD', 'WD Blue', 'M2 SATA', '2 TB', 'SSD WD WD Blue 2 TB');
INSERT IGNORE INTO `pc_parts_picker`.ssd VALUES ('wd-blue-sn550-250-m2-nvme', 'WD', 'Blue SN550', 'M2 NVMe', '250 GB', 'SSD WD Blue SN550 250 GB');
INSERT IGNORE INTO `pc_parts_picker`.ssd VALUES ('seagate-firecuda-520-2048-m2-nvme', 'Seagate', 'FireCuda 520', 'M2 NVMe', '2 TB', 'SSD Seagate FireCuda 520 2 TB');
INSERT IGNORE INTO `pc_parts_picker`.ssd VALUES ('wd-black-sn850-1024-m2-nvme', 'WD', 'Black SN850', 'M2 NVMe', '1 TB', 'SSD WD Black SN850 1 TB');
INSERT IGNORE INTO `pc_parts_picker`.ssd VALUES ('seagate-firecuda-520-1024-m2-nvme', 'Seagate', 'FireCuda 520', 'M2 NVMe', '1 TB', 'SSD Seagate FireCuda 520 1 TB');
INSERT IGNORE INTO `pc_parts_picker`.ssd VALUES ('wd-green-240-m2-sata', 'WD', 'Green', 'M2 SATA', '240 GB', 'SSD WD Green 240 GB');
INSERT IGNORE INTO `pc_parts_picker`.ssd VALUES ('wd-black-sn850-2048-m2-nvme', 'WD', 'Black SN850', 'M2 NVMe', '2 TB', 'SSD WD Black SN850 2 TB');
INSERT IGNORE INTO `pc_parts_picker`.ssd VALUES ('wd-green-120-m2-sata', 'WD', 'Green', 'M2 SATA', '120 GB', 'SSD WD Green 120 GB');
INSERT IGNORE INTO `pc_parts_picker`.ssd VALUES ('wd-sn750-2048-m2-nvme', 'WD', 'SN750', 'M2 NVMe', '2 TB', 'SSD WD SN750 2 TB');
INSERT IGNORE INTO `pc_parts_picker`.ssd VALUES ('seagate-firecuda-520-500-m2-nvme', 'Seagate', 'FireCuda 520', 'M2 NVMe', '500 GB', 'SSD Seagate FireCuda 520 500 GB');
INSERT IGNORE INTO `pc_parts_picker`.ssd VALUES ('wd-blue-250-m2-sata', 'WD', 'Blue', 'M2 SATA', '250 GB', 'SSD WD Blue 250 GB');
INSERT IGNORE INTO `pc_parts_picker`.ssd VALUES ('wd-sn750-250-m2-nvme', 'WD', 'SN750', 'M2 NVMe', '250 GB', 'SSD WD SN750 250 GB');
INSERT IGNORE INTO `pc_parts_picker`.ssd VALUES ('seagate-barracuda-120-1024-m2-sata', 'Seagate', 'BarraCuda 120', 'M2 SATA', '1 TB', 'SSD Seagate BarraCuda 120 1 TB');
INSERT IGNORE INTO `pc_parts_picker`.ssd VALUES ('wd-sn750-1024-m2-nvme', 'WD', 'SN750', 'M2 NVMe', '1 TB', 'SSD WD SN750 1 TB');
INSERT IGNORE INTO `pc_parts_picker`.ssd VALUES ('seagate-barracuda-120-500-m2-sata', 'Seagate', 'BarraCuda 120', 'M2 SATA', '500 GB', 'SSD Seagate BarraCuda 120 500 GB');
INSERT IGNORE INTO `pc_parts_picker`.ssd VALUES ('seagate-barracuda-510-1024-m2-nvme', 'Seagate', 'BarraCuda 510', 'M2 NVMe', '1 TB', 'SSD Seagate BarraCuda 510 1 TB');
INSERT IGNORE INTO `pc_parts_picker`.ssd VALUES ('wd-green-120-m2-sata', 'WD', 'Green', 'M2 SATA', '120 GB', 'SSD WD Green 120 GB');
INSERT IGNORE INTO `pc_parts_picker`.ssd VALUES ('wd-green-480-m2-sata', 'WD', 'Green', 'M2 SATA', '480 GB', 'SSD WD Green 480 GB');
INSERT IGNORE INTO `pc_parts_picker`.ssd VALUES ('wd-blue-4096-m2-sata', 'WD', 'Blue', 'M2 SATA', '4 TB', 'SSD WD Blue 4 TB');
INSERT IGNORE INTO `pc_parts_picker`.ssd VALUES ('seagate-barracuda-510-500-m2-nvme', 'Seagate', 'BarraCuda 510', 'M2 NVMe', '500 GB', 'SSD Seagate BarraCuda 510 500 GB');
INSERT IGNORE INTO `pc_parts_picker`.ssd VALUES ('wd-sn750-500-m2-nvme', 'WD', 'SN750', 'M2 NVMe', '500 GB', 'SSD WD SN750 500 GB');
INSERT IGNORE INTO `pc_parts_picker`.ssd VALUES ('wd-green-480-m2-sata', 'WD', 'Green', 'M2 SATA', '480 GB', 'SSD WD Green 480 GB');
INSERT IGNORE INTO `pc_parts_picker`.ssd VALUES ('wd-black-sn850-500-m2-nvme', 'WD', 'Black SN850', 'M2 NVMe', '500 GB', 'SSD WD Black SN850 500 GB');
INSERT IGNORE INTO `pc_parts_picker`.ssd VALUES ('wd-sn750-2048-m2-nvme', 'WD', 'SN750', 'M2 NVMe', '2 TB', 'SSD WD SN750 2 TB');
INSERT IGNORE INTO `pc_parts_picker`.ssd VALUES ('wd-black-nvme-1024-m2-nvme', 'WD', 'Black NVMe', 'M2 NVMe', '1 TB', 'SSD WD Black NVMe 1 TB');
INSERT IGNORE INTO `pc_parts_picker`.ssd VALUES ('wd-black-nvme-500-m2-nvme', 'WD', 'Black NVMe', 'M2 NVMe', '500 GB', 'SSD WD Black NVMe 500 GB');
INSERT IGNORE INTO `pc_parts_picker`.ssd VALUES ('seagate-barracuda-120-250-m2-sata', 'Seagate', 'BarraCuda 120', 'M2 SATA', '250 GB', 'SSD Seagate BarraCuda 120 250 GB');
INSERT IGNORE INTO `pc_parts_picker`.ssd VALUES ('seagate-barracuda-120-2048-m2-sata', 'Seagate', 'BarraCuda 120', 'M2 SATA', '2 TB', 'SSD Seagate BarraCuda 120 2 TB');
INSERT IGNORE INTO `pc_parts_picker`.ssd VALUES ('wd-black-pcie-256-m2-nvme', 'WD', 'Black PCIe', 'M2 NVMe', '256 GB', 'SSD WD Black PCIe 256 GB');
INSERT IGNORE INTO `pc_parts_picker`.ssd VALUES ('seagate-firecuda-1024-m2-nvme', 'Seagate', 'FireCuda', 'M2 NVMe', '1 TB', 'SSD Seagate FireCuda 1 TB');
INSERT IGNORE INTO `pc_parts_picker`.ssd VALUES ('seagate-nytro-enterprise-15728.64-m2-sata', 'Seagate', 'Nytro Enterprise', 'M2 SATA', '15.36 TB', 'SSD Seagate Nytro Enterprise 15.36 TB');
INSERT IGNORE INTO `pc_parts_picker`.ssd VALUES ('seagate-firecuda-510-500-m2-nvme', 'Seagate', 'FireCuda 510', 'M2 NVMe', '500 GB', 'SSD Seagate FireCuda 510 500 GB');
INSERT IGNORE INTO `pc_parts_picker`.ssd VALUES ('wd-blue-sn500-500-m2-sata', 'WD', 'Blue SN500', 'M2 SATA', '500 GB', 'SSD WD Blue SN500 500 GB');
INSERT IGNORE INTO `pc_parts_picker`.ssd VALUES ('seagate-barracuda-510-250-m2-nvme', 'Seagate', 'BarraCuda 510', 'M2 NVMe', '250 GB', 'SSD Seagate BarraCuda 510 250 GB');
INSERT IGNORE INTO `pc_parts_picker`.ssd VALUES ('wd-black-sn850-(w/heatsink)-2048-m2-nvme', 'WD', 'Black SN850 (w/Heatsink)', 'M2 NVMe', '2 TB', 'SSD WD Black SN850 (w/Heatsink) 2 TB');
INSERT IGNORE INTO `pc_parts_picker`.ssd VALUES ('seagate-firecuda-2048-m2-nvme', 'Seagate', 'FireCuda', 'M2 NVMe', '2 TB', 'SSD Seagate FireCuda 2 TB');
INSERT IGNORE INTO `pc_parts_picker`.ssd VALUES ('wd-blue-500-m2-sata', 'WD', 'Blue', 'M2 SATA', '500 GB', 'SSD WD Blue 500 GB');
INSERT IGNORE INTO `pc_parts_picker`.ssd VALUES ('wd-blue-sn500-250-m2-sata', 'WD', 'Blue SN500', 'M2 SATA', '250 GB', 'SSD WD Blue SN500 250 GB');
INSERT IGNORE INTO `pc_parts_picker`.ssd VALUES ('wd-black-sn850-(w/heatsink)-1024-m2-nvme', 'WD', 'Black SN850 (w/Heatsink)', 'M2 NVMe', '1 TB', 'SSD WD Black SN850 (w/Heatsink) 1 TB');
INSERT IGNORE INTO `pc_parts_picker`.ssd VALUES ('wd-black-nvme-250-m2-nvme', 'WD', 'Black NVMe', 'M2 NVMe', '250 GB', 'SSD WD Black NVMe 250 GB');
INSERT IGNORE INTO `pc_parts_picker`.ssd VALUES ('seagate-barracuda-compute-2048-m2-sata', 'Seagate', 'BarraCuda Compute', 'M2 SATA', '2 TB', 'SSD Seagate BarraCuda Compute 2 TB');
INSERT IGNORE INTO `pc_parts_picker`.ssd VALUES ('seagate-ironwolf-nas-3932.16-m2-sata', 'Seagate', 'IronWolf NAS', 'M2 SATA', '3.84 TB', 'SSD Seagate IronWolf NAS 3.84 TB');
INSERT IGNORE INTO `pc_parts_picker`.ssd VALUES ('wd-green-240-m2-sata', 'WD', 'Green', 'M2 SATA', '240 GB', 'SSD WD Green 240 GB');
INSERT IGNORE INTO `pc_parts_picker`.ssd VALUES ('wd-red-sa500-4096-m2-sata', 'WD', 'Red SA500', 'M2 SATA', '4 TB', 'SSD WD Red SA500 4 TB');
INSERT IGNORE INTO `pc_parts_picker`.ssd VALUES ('wd-blue-250-m2-sata', 'WD', 'Blue', 'M2 SATA', '250 GB', 'SSD WD Blue 250 GB');
INSERT IGNORE INTO `pc_parts_picker`.ssd VALUES ('wd-black-512-m2-nvme', 'WD', 'Black', 'M2 NVMe', '512 GB', 'SSD WD Black 512 GB');
INSERT IGNORE INTO `pc_parts_picker`.ssd VALUES ('wd-blue-1024-m2-sata', 'WD', 'Blue', 'M2 SATA', '1 TB', 'SSD WD Blue 1 TB');
INSERT IGNORE INTO `pc_parts_picker`.ssd VALUES ('seagate-barracuda-compute-1024-m2-sata', 'Seagate', 'BarraCuda Compute', 'M2 SATA', '1 TB', 'SSD Seagate BarraCuda Compute 1 TB');
INSERT IGNORE INTO `pc_parts_picker`.ssd VALUES ('wd-sn520-256-m2-sata', 'WD', 'SN520', 'M2 SATA', '256 GB', 'SSD WD SN520 256 GB');
INSERT IGNORE INTO `pc_parts_picker`.ssd VALUES ('wd-blue-250-m2-sata', 'WD', 'Blue', 'M2 SATA', '250 GB', 'SSD WD Blue 250 GB');
INSERT IGNORE INTO `pc_parts_picker`.ssd VALUES ('seagate-barracuda-compute-256-m2-nvme', 'Seagate', 'Barracuda Compute', 'M2 NVMe', '256 GB', 'SSD Seagate Barracuda Compute 256 GB');
INSERT IGNORE INTO `pc_parts_picker`.ssd VALUES ('wd-green-240-m2-sata', 'WD', 'Green', 'M2 SATA', '240 GB', 'SSD WD Green 240 GB');
INSERT IGNORE INTO `pc_parts_picker`.ssd VALUES ('wd-red-sa500-1024-m2-sata', 'WD', 'Red SA500', 'M2 SATA', '1 TB', 'SSD WD Red SA500 1 TB');
INSERT IGNORE INTO `pc_parts_picker`.ssd VALUES ('wd-blue-250-m2-sata', 'WD', 'Blue', 'M2 SATA', '250 GB', 'SSD WD Blue 250 GB');
INSERT IGNORE INTO `pc_parts_picker`.ssd VALUES ('wd-blue-1024-m2-sata', 'WD', 'Blue', 'M2 SATA', '1 TB', 'SSD WD Blue 1 TB');
INSERT IGNORE INTO `pc_parts_picker`.ssd VALUES ('wd-red-sa500-2048-m2-sata', 'WD', 'Red SA500', 'M2 SATA', '2 TB', 'SSD WD Red SA500 2 TB');
INSERT IGNORE INTO `pc_parts_picker`.ssd VALUES ('wd-red-sa500-1024-m2-sata', 'WD', 'Red SA500', 'M2 SATA', '1 TB', 'SSD WD Red SA500 1 TB');
INSERT IGNORE INTO `pc_parts_picker`.ssd VALUES ('wd-black-sn850-(w/heatsink)-500-m2-nvme', 'WD', 'Black SN850 (w/Heatsink)', 'M2 NVMe', '500 GB', 'SSD WD Black SN850 (w/Heatsink) 500 GB');
INSERT IGNORE INTO `pc_parts_picker`.ssd VALUES ('wd-red-sa500-2048-m2-sata', 'WD', 'Red SA500', 'M2 SATA', '2 TB', 'SSD WD Red SA500 2 TB');
INSERT IGNORE INTO `pc_parts_picker`.ssd VALUES ('wd-red-sa500-500-m2-sata', 'WD', 'Red SA500', 'M2 SATA', '500 GB', 'SSD WD Red SA500 500 GB');
INSERT IGNORE INTO `pc_parts_picker`.ssd VALUES ('seagate-barracuda-computer-1024-m2-sata', 'Seagate', 'Barracuda Computer', 'M2 SATA', '1 TB', 'SSD Seagate Barracuda Computer 1 TB');
INSERT IGNORE INTO `pc_parts_picker`.ssd VALUES ('seagate-barracuda-compute-2048-m2-sata', 'Seagate', 'BarraCuda Compute', 'M2 SATA', '2 TB', 'SSD Seagate BarraCuda Compute 2 TB');
INSERT IGNORE INTO `pc_parts_picker`.ssd VALUES ('seagate-barracuda-120-250-m2-sata', 'Seagate', 'BarraCuda 120', 'M2 SATA', '250 GB', 'SSD Seagate BarraCuda 120 250 GB');
INSERT IGNORE INTO `pc_parts_picker`.ssd VALUES ('seagate-barracuda-compute-512-m2-nvme', 'Seagate', 'Barracuda Compute', 'M2 NVMe', '512 GB', 'SSD Seagate Barracuda Compute 512 GB');
INSERT IGNORE INTO `pc_parts_picker`.ssd VALUES ('wd-blue-500-m2-sata', 'WD', 'Blue', 'M2 SATA', '500 GB', 'SSD WD Blue 500 GB');
INSERT IGNORE INTO `pc_parts_picker`.ssd VALUES ('wd-green-120-m2-sata', 'WD', 'Green', 'M2 SATA', '120 GB', 'SSD WD Green 120 GB');
INSERT IGNORE INTO `pc_parts_picker`.ssd VALUES ('seagate-nytro-5000-400-m2-nvme', 'Seagate', 'Nytro 5000', 'M2 NVMe', '400 GB', 'SSD Seagate Nytro 5000 400 GB');
INSERT IGNORE INTO `pc_parts_picker`.ssd VALUES ('seagate-600-series-240-m2-sata', 'Seagate', '600 Series', 'M2 SATA', '240 GB', 'SSD Seagate 600 Series 240 GB');
INSERT IGNORE INTO `pc_parts_picker`.ssd VALUES ('seagate-barracuda-compute-500-m2-sata', 'Seagate', 'BarraCuda Compute', 'M2 SATA', '500 GB', 'SSD Seagate BarraCuda Compute 500 GB');
INSERT IGNORE INTO `pc_parts_picker`.ssd VALUES ('seagate-barracuda-compute-500-m2-sata', 'Seagate', 'Barracuda Compute', 'M2 SATA', '500 GB', 'SSD Seagate Barracuda Compute 500 GB');
INSERT IGNORE INTO `pc_parts_picker`.ssd VALUES ('seagate-barracuda-compute-250-m2-sata', 'Seagate', 'Barracuda Compute', 'M2 SATA', '250 GB', 'SSD Seagate Barracuda Compute 250 GB');
INSERT IGNORE INTO `pc_parts_picker`.ssd VALUES ('seagate-ironwolf-510-1966.08-m2-nvme', 'Seagate', 'IronWolf 510', 'M2 NVMe', '1.92 TB', 'SSD Seagate IronWolf 510 1.92 TB');
INSERT IGNORE INTO `pc_parts_picker`.ssd VALUES ('seagate-ironwolf-nas-240-m2-sata', 'Seagate', 'IronWolf NAS', 'M2 SATA', '240 GB', 'SSD Seagate IronWolf NAS 240 GB');
INSERT IGNORE INTO `pc_parts_picker`.ssd VALUES ('seagate-nytro-enterprise-3932.16-m2-sata', 'Seagate', 'Nytro Enterprise', 'M2 SATA', '3.84 TB', 'SSD Seagate Nytro Enterprise 3.84 TB');
INSERT IGNORE INTO `pc_parts_picker`.ssd VALUES ('wd-sn520-512-m2-sata', 'WD', 'SN520', 'M2 SATA', '512 GB', 'SSD WD SN520 512 GB');
INSERT IGNORE INTO `pc_parts_picker`.ssd VALUES ('seagate-barracuda-compute-1024-m2-sata', 'Seagate', 'Barracuda Compute', 'M2 SATA', '1 TB', 'SSD Seagate Barracuda Compute 1 TB');
INSERT IGNORE INTO `pc_parts_picker`.ssd VALUES ('seagate-ironwolf-nas-480-m2-sata', 'Seagate', 'IronWolf NAS', 'M2 SATA', '480 GB', 'SSD Seagate IronWolf NAS 480 GB');
INSERT IGNORE INTO `pc_parts_picker`.ssd VALUES ('wd-siliconedge-blue-256-m2-sata', 'WD', 'SiliconEdge Blue', 'M2 SATA', '256 GB', 'SSD WD SiliconEdge Blue 256 GB');
INSERT IGNORE INTO `pc_parts_picker`.ssd VALUES ('seagate-ironwolf-510-240-m2-nvme', 'Seagate', 'IronWolf 510', 'M2 NVMe', '240 GB', 'SSD Seagate IronWolf 510 240 GB');
INSERT IGNORE INTO `pc_parts_picker`.ssd VALUES ('seagate-nytro-enterprise-1966.08-m2-nvme', 'Seagate', 'Nytro Enterprise', 'M2 NVMe', '1.92 TB', 'SSD Seagate Nytro Enterprise 1.92 TB');
INSERT IGNORE INTO `pc_parts_picker`.ssd VALUES ('seagate-ironwolf-nas-960-m2-sata', 'Seagate', 'IronWolf NAS', 'M2 SATA', '960 GB', 'SSD Seagate IronWolf NAS 960 GB');
INSERT IGNORE INTO `pc_parts_picker`.ssd VALUES ('seagate-barracuda-compute-250-m2-sata', 'Seagate', 'BarraCuda Compute', 'M2 SATA', '250 GB', 'SSD Seagate BarraCuda Compute 250 GB');
INSERT IGNORE INTO `pc_parts_picker`.ssd VALUES ('seagate-barracuda-compute-500-m2-sata', 'Seagate', 'BarraCuda Compute', 'M2 SATA', '500 GB', 'SSD Seagate BarraCuda Compute 500 GB');
INSERT IGNORE INTO `pc_parts_picker`.ssd VALUES ('seagate-firecuda-120-4096-m2-sata', 'Seagate', 'FireCuda 120', 'M2 SATA', '4 TB', 'SSD Seagate FireCuda 120 4 TB');
INSERT IGNORE INTO `pc_parts_picker`.ssd VALUES ('seagate-600-series-120-m2-sata', 'Seagate', '600 Series', 'M2 SATA', '120 GB', 'SSD Seagate 600 Series 120 GB');
INSERT IGNORE INTO `pc_parts_picker`.ssd VALUES ('seagate-600-series--m2-sata', 'Seagate', '600 Series', 'M2 SATA', '480 GB', 'SSD Seagate 600 Series 480 GB');
INSERT IGNORE INTO `pc_parts_picker`.ssd VALUES ('seagate-nytro-enterprise--m2-sata', 'Seagate', 'Nytro Enterprise', 'M2 SATA', '1.92 TB', 'SSD Seagate Nytro Enterprise 1.92 TB');
INSERT IGNORE INTO `pc_parts_picker`.ssd VALUES ('seagate-nytro-enterprise--m2-sata', 'Seagate', 'Nytro Enterprise', 'M2 SATA', '960 GB', 'SSD Seagate Nytro Enterprise 960 GB');
 