INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('asrock-b450m-steel-legend', 'ASRock', 'B450M Steel Legend', '', 'AM4', '64 GB', 'ASRock B450M Steel Legend');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('asus-ex-b360m-v5', 'Asus', 'EX-B360M-V5', '', 'LGA1151', '32 GB', 'Asus EX-B360M-V5');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('asus-tuf-gaming-b460-plus', 'Asus', 'TUF GAMING B460-PLUS', '5', 'LGA1200', '128 GB', 'Asus TUF GAMING B460-PLUS');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('gigabyte-b450-aorus-m', 'Gigabyte', 'B450 AORUS M', '4', 'AM4', '64 GB', 'Gigabyte B450 AORUS M');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('asus-prime-a320m-k', 'Asus', 'PRIME A320M-K', '4', 'AM4', '32 GB', 'Asus PRIME A320M-K');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('msi-b450m-mortar-max', 'MSI', 'B450M MORTAR MAX', '3', 'AM4', '64 GB', 'MSI B450M MORTAR MAX');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('asus-rog-strix-b550-f-gaming-(wi-fi)', 'Asus', 'ROG STRIX B550-F GAMING (WI-FI)', '3', 'AM4', '128 GB', 'Asus ROG STRIX B550-F GAMING (WI-FI)');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('asus-rog-strix-b550-f-gaming', 'Asus', 'ROG STRIX B550-F GAMING', '3', 'AM4', '128 GB', 'Asus ROG STRIX B550-F GAMING');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('asus-rog-maximus-xii-formula', 'Asus', 'ROG MAXIMUS XII FORMULA', 'Z490', 'LGA1200', '128 GB', 'Asus ROG MAXIMUS XII FORMULA');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('asrock-b365-phantom-gaming-4', 'ASRock', 'B65 Phantom Gaming 4', '3', 'LGA1151', '128 GB', 'ASRock B365 Phantom Gaming 4');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('gigabyte-b365-m-aorus-elite', 'Gigabyte', 'B65 M AORUS ELITE', '3', 'LGA1151', '64 GB', 'Gigabyte B365 M AORUS ELITE');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('asrock-b460-pro4', 'ASRock', 'B460 Pro4', '3', 'LGA1200', '128 GB', 'ASRock B460 Pro4');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('msi-mag-b460-tomahawk', 'MSI', 'MAG B460 TOMAHAWK', '3', 'LGA1200', '128 GB', 'MSI MAG B460 TOMAHAWK');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('gigabyte-b460-aorus-pro-ac', 'Gigabyte', 'B460 AORUS PRO AC', '3', 'LGA1200', '128 GB', 'Gigabyte B460 AORUS PRO AC');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('asrock-b460-steel-legend', 'ASRock', 'B460 Steel Legend', '3', 'LGA1200', '128 GB', 'ASRock B460 Steel Legend');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('asus-rog-strix-b460-f-gaming', 'Asus', 'ROG STRIX B460-F GAMING', '3', 'LGA1200', '128 GB', 'Asus ROG STRIX B460-F GAMING');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('asus-rog-strix-b460-g-gaming', 'Asus', 'ROG STRIX B460-G GAMING', '3', 'LGA1200', '128 GB', 'Asus ROG STRIX B460-G GAMING');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('asus-rog-strix-b460-h-gaming', 'Asus', 'ROG STRIX B460-H GAMING', '3', 'LGA1200', '128 GB', 'Asus ROG STRIX B460-H GAMING');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('asus-rog-strix-b460-i-gaming', 'Asus', 'ROG STRIX B460-I GAMING', '3', 'LGA1200', '64 GB', 'Asus ROG STRIX B460-I GAMING');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('msi-mag-b460m-mortar', 'MSI', 'MAG B460M MORTAR', '3', 'LGA1200', '128 GB', 'MSI MAG B460M MORTAR');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('asrock-b550-steel-legend', 'ASRock', 'B550 Steel Legend', '3', 'AM4', '128 GB', 'ASRock B550 Steel Legend');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('gigabyte-b550i-aorus-pro-ax', 'Gigabyte', 'B550I AORUS PRO AX', '3', 'AM4', '64 GB', 'Gigabyte B550I AORUS PRO AX');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('asrock-b550m-steel-legend', 'ASRock', 'B550M Steel Legend', '3', 'AM4', '128 GB', 'ASRock B550M Steel Legend');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('gigabyte-h310m-ds2', 'Gigabyte', 'H10M DS2', '3', 'LGA1151', '32 GB', 'Gigabyte H310M DS2');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('msi-mpg-x570-gaming-edge-wifi', 'MSI', 'MPG X570 GAMING EDGE WIFI', '3', 'AM4', '128 GB', 'MSI MPG X570 GAMING EDGE WIFI');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('gigabyte-x570-aorus-ultra', 'Gigabyte', 'X570 AORUS ULTRA', '3', 'AM4', '128 GB', 'Gigabyte X570 AORUS ULTRA');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('asrock-x570-taichi', 'ASRock', 'X570 Taichi', '3', 'AM4', '128 GB', 'ASRock X570 Taichi');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('msi-mag-z490-tomahawk', 'MSI', 'MAG Z490 TOMAHAWK', '3', 'LGA1200', '128 GB', 'MSI MAG Z490 TOMAHAWK');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('gigabyte-z490-vision-g', 'Gigabyte', 'Z490 VISION G', '3', 'LGA1200', '128 GB', 'Gigabyte Z490 VISION G');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('gigabyte-z490-ud', 'Gigabyte', 'Z490 UD', '3', 'LGA1200', '128 GB', 'Gigabyte Z490 UD');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('asrock-z490-extreme4', 'ASRock', 'Z490 Extreme4', '3', 'LGA1200', '128 GB', 'ASRock Z490 Extreme4');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('asrock-z490-steel-legend', 'ASRock', 'Z490 Steel Legend', '3', 'LGA1200', '128 GB', 'ASRock Z490 Steel Legend');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('asus-rog-strix-z490-f-gaming', 'Asus', 'ROG STRIX Z490-F GAMING', '3', 'LGA1200', '128 GB', 'Asus ROG STRIX Z490-F GAMING');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('asus-rog-strix-z490-h-gaming', 'Asus', 'ROG STRIX Z490-H GAMING', '3', 'LGA1200', '128 GB', 'Asus ROG STRIX Z490-H GAMING');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('asus-prime-z490-p', 'Asus', 'PRIME Z490-P', '3', 'LGA1200', '128 GB', 'Asus PRIME Z490-P');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('asrock-b550m-itx/ac', 'ASRock', 'B550M-ITX/ac', '3', 'AM4', '64 GB', 'ASRock B550M-ITX/ac');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('asus-rog-maximus-xii-hero-(wi-fi)', 'Asus', 'ROG MAXIMUS XII HERO (WI-FI)', 'Z490', 'LGA1200', '128 GB', 'Asus ROG MAXIMUS XII HERO (WI-FI)');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('asus-rog-maximus-xii-extreme', 'Asus', 'ROG MAXIMUS XII EXTREME', 'Z490', 'LGA1200', '128 GB', 'Asus ROG MAXIMUS XII EXTREME');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('asus-rog-maximus-xii-apex', 'Asus', 'ROG MAXIMUS XII APEX', 'Z490', 'LGA1200', '64 GB', 'Asus ROG MAXIMUS XII APEX');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('asus-rog-crosshair-viii-hero-(wi-fi)', 'Asus', 'ROG Crosshair VIII Hero (WI-FI)', 'X570', 'AM4', '128 GB', 'Asus ROG Crosshair VIII Hero (WI-FI)');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('asus-rog-crosshair-viii-hero', 'Asus', 'ROG Crosshair VIII Hero', 'X570', 'AM4', '128 GB', 'Asus ROG Crosshair VIII Hero');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('asus-rog-crosshair-viii-formula', 'Asus', 'ROG Crosshair VIII Formula', 'X570', 'AM4', '128 GB', 'Asus ROG Crosshair VIII Formula');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('asrock-a320m-hdv-r4.0', 'ASRock', 'A30M-HDV R4.0', '2', 'AM4', '32 GB', 'ASRock A320M-HDV R4.0');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('asrock-b365-pro4', 'ASRock', 'B365 Pro4', '2', 'LGA1151', '64 GB', 'ASRock B365 Pro4');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('asus-rog-strix-b365-g-gaming', 'Asus', 'ROG STRIX B365-G GAMING', '2', 'LGA1151', '64 GB', 'Asus ROG STRIX B365-G GAMING');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('gigabyte-b365m-d2v', 'Gigabyte', 'B365M DV', '2', 'LGA1151', '32 GB', 'Gigabyte B365M D2V');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('msi-b450-tomahawk-max', 'MSI', 'B450 TOMAHAWK MAX', '2', 'AM4', '64 GB', 'MSI B450 TOMAHAWK MAX');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('asrock-b450m-pro4-f', 'ASRock', 'B450M Pro4-F', '2', 'AM4', '64 GB', 'ASRock B450M Pro4-F');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('msi-b450m-bazooka-plus', 'MSI', 'B450M BAZOOKA PLUS', '2', 'AM4', '64 GB', 'MSI B450M BAZOOKA PLUS');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('asrock-b460-phantom-gaming-4', 'ASRock', 'B460 Phantom Gaming 4', '2', 'LGA1200', '128 GB', 'ASRock B460 Phantom Gaming 4');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('asrock-b460m-pro4', 'ASRock', 'B460M Pro4', '2', 'LGA1200', '128 GB', 'ASRock B460M Pro4');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('msi-mag-b460m-bazooka', 'MSI', 'MAG B460M BAZOOKA', '2', 'LGA1200', '128 GB', 'MSI MAG B460M BAZOOKA');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('msi-mag-b460m-mortar-wifi', 'MSI', 'MAG B460M MORTAR WIFI', '2', 'LGA1200', '128 GB', 'MSI MAG B460M MORTAR WIFI');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('asrock-b460m-steel-legend', 'ASRock', 'B460M Steel Legend', '2', 'LGA1200', '128 GB', 'ASRock B460M Steel Legend');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('asus-tuf-gaming-b460m-plus-(wi-fi)', 'Asus', 'TUF GAMING B460M-PLUS (WI-FI)', '2', 'LGA1200', '128 GB', 'Asus TUF GAMING B460M-PLUS (WI-FI)');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('asus-tuf-gaming-b460m-plus', 'Asus', 'TUF GAMING B460M-PLUS', '2', 'LGA1200', '128 GB', 'Asus TUF GAMING B460M-PLUS');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('asus-tuf-gaming-b460-pro-(wi-fi)', 'Asus', 'TUF GAMING B460-PRO (WI-FI)', '2', 'LGA1200', '128 GB', 'Asus TUF GAMING B460-PRO (WI-FI)');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('gigabyte-b550-aorus-elite', 'Gigabyte', 'B550 AORUS ELITE', '2', 'AM4', '128 GB', 'Gigabyte B550 AORUS ELITE');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('gigabyte-b550-aorus-master', 'Gigabyte', 'B550 AORUS MASTER', '2', 'AM4', '128 GB', 'Gigabyte B550 AORUS MASTER');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('asrock-b550-taichi', 'ASRock', 'B550 Taichi', '2', 'AM4', '128 GB', 'ASRock B550 Taichi');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('asus-rog-strix-b550-i-gaming', 'Asus', 'ROG STRIX B550-I GAMING', '2', 'AM4', '64 GB', 'Asus ROG STRIX B550-I GAMING');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('asrock-b550m-pro4', 'ASRock', 'B550M Pro4', '2', 'AM4', '128 GB', 'ASRock B550M Pro4');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('msi-mag-b550m-mortar', 'MSI', 'MAG B550M MORTAR', '2', 'AM4', '128 GB', 'MSI MAG B550M MORTAR');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('asrock-h310cm-dvs', 'ASRock', 'H310CM-DVS', '2', 'LGA1151', '32 GB', 'ASRock H310CM-DVS');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('asrock-h310cm-hdv/m.2', 'ASRock', 'H310CM-HDV/M.', '2', 'LGA1151', '32 GB', 'ASRock H310CM-HDV/M.2');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('msi-h310m-pro-vdh-plus', 'MSI', 'H310M PRO-VDH PLUS', '2', 'LGA1151', '32 GB', 'MSI H310M PRO-VDH PLUS');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('gigabyte-h410m-ds2v', 'Gigabyte', 'H410M DSV', '2', 'LGA1200', '64 GB', 'Gigabyte H410M DS2V');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('asus-prime-h410m-d', 'Asus', 'PRIME H410M-D', '2', 'LGA1200', '64 GB', 'Asus PRIME H410M-D');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('asus-prime-h410m-e', 'Asus', 'PRIME H410M-E', '2', 'LGA1200', '64 GB', 'Asus PRIME H410M-E');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('asrock-h410m-hdv/m.2', 'ASRock', 'H410M-HDV/M.', '2', 'LGA1200', '64 GB', 'ASRock H410M-HDV/M.2');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('asrock-h410m-hvs', 'ASRock', 'H410M-HVS', '2', 'LGA1200', '64 GB', 'ASRock H410M-HVS');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('asus-prime-h410m-k', 'Asus', 'PRIME H410M-K', '2', 'LGA1200', '64 GB', 'Asus PRIME H410M-K');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('msi-mpg-x570-gaming-pro-carbon-wifi', 'MSI', 'MPG X570 GAMING PRO CARBON WIFI', '2', 'AM4', '128 GB', 'MSI MPG X570 GAMING PRO CARBON WIFI');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('gigabyte-x570-aorus-master', 'Gigabyte', 'X570 AORUS MASTER', '2', 'AM4', '128 GB', 'Gigabyte X570 AORUS MASTER');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('msi-meg-x570-godlike', 'MSI', 'MEG X570 GODLIKE', '2', 'AM4', '128 GB', 'MSI MEG X570 GODLIKE');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('msi-meg-x570-ace', 'MSI', 'MEG X570 ACE', '2', 'AM4', '128 GB', 'MSI MEG X570 ACE');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('gigabyte-x570-ud', 'Gigabyte', 'X570 UD', '2', 'AM4', '128 GB', 'Gigabyte X570 UD');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('asrock-x570-steel-legend', 'ASRock', 'X570 Steel Legend', '2', 'AM4', '128 GB', 'ASRock X570 Steel Legend');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('msi-prestige-x570-creation', 'MSI', 'PRESTIGE X570 CREATION', '2', 'AM4', '128 GB', 'MSI PRESTIGE X570 CREATION');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('asus-rog-strix-x570-f-gaming', 'Asus', 'ROG Strix X570-F Gaming', '2', 'AM4', '128 GB', 'Asus ROG Strix X570-F Gaming');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('msi-mpg-z390-gaming-edge-ac', 'MSI', 'MPG Z390 GAMING EDGE AC', '2', 'LGA1151', '128 GB', 'MSI MPG Z390 GAMING EDGE AC');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('msi-mag-z390-tomahawk', 'MSI', 'MAG Z390 TOMAHAWK', '2', 'LGA1151', '128 GB', 'MSI MAG Z390 TOMAHAWK');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('asrock-z390-steel-legend', 'ASRock', 'Z390 STEEL LEGEND', '2', 'LGA1151', '128 GB', 'ASRock Z390 STEEL LEGEND');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('gigabyte-z390-aorus-master', 'Gigabyte', 'Z390 AORUS MASTER', '2', 'LGA1151', '128 GB', 'Gigabyte Z390 AORUS MASTER');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('asus-rog-strix-z390-f-gaming', 'Asus', 'ROG STRIX Z390-F GAMING', '2', 'LGA1151', '128 GB', 'Asus ROG STRIX Z390-F GAMING');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('asus-rog-strix-z390-h-gaming', 'Asus', 'ROG STRIX Z390-H GAMING', '2', 'LGA1151', '128 GB', 'Asus ROG STRIX Z390-H GAMING');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('msi-mpg-z390i-gaming-edge-ac', 'MSI', 'MPG Z390I GAMING EDGE AC', '2', 'LGA1151', '64 GB', 'MSI MPG Z390I GAMING EDGE AC');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('asus-prime-z390m-plus', 'Asus', 'PRIME Z390M-PLUS', '2', 'LGA1151', '128 GB', 'Asus PRIME Z390M-PLUS');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('asus-prime-z390-p', 'Asus', 'PRIME Z390-P', '2', 'LGA1151', '128 GB', 'Asus PRIME Z390-P');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('msi-mpg-z490-gaming-plus', 'MSI', 'MPG Z490 GAMING PLUS', '2', 'LGA1200', '128 GB', 'MSI MPG Z490 GAMING PLUS');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('msi-mpg-z490-gaming-edge-wifi', 'MSI', 'MPG Z490 GAMING EDGE WIFI', '2', 'LGA1200', '128 GB', 'MSI MPG Z490 GAMING EDGE WIFI');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('msi-meg-z490-unify', 'MSI', 'MEG Z490 UNIFY', '2', 'LGA1200', '128 GB', 'MSI MEG Z490 UNIFY');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('gigabyte-z490-aorus-ultra', 'Gigabyte', 'Z490 AORUS ULTRA', '2', 'LGA1200', '128 GB', 'Gigabyte Z490 AORUS ULTRA');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('msi-meg-z490-godlike', 'MSI', 'MEG Z490 GODLIKE', '2', 'LGA1200', '128 GB', 'MSI MEG Z490 GODLIKE');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('gigabyte-z490-aorus-master', 'Gigabyte', 'Z490 AORUS MASTER', '2', 'LGA1200', '128 GB', 'Gigabyte Z490 AORUS MASTER');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('gigabyte-z490-aorus-xtreme-waterforce', 'Gigabyte', 'Z490 AORUS XTREME WATERFORCE', '2', 'LGA1200', '128 GB', 'Gigabyte Z490 AORUS XTREME WATERFORCE');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('gigabyte-z490-aorus-pro-ax', 'Gigabyte', 'Z490 AORUS PRO AX', '2', 'LGA1200', '128 GB', 'Gigabyte Z490 AORUS PRO AX');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('asrock-z490-phantom-gaming-4', 'ASRock', 'Z490 Phantom Gaming 4', '2', 'LGA1200', '128 GB', 'ASRock Z490 Phantom Gaming 4');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('msi-meg-z490-ace', 'MSI', 'MEG Z490 ACE', '2', 'LGA1200', '128 GB', 'MSI MEG Z490 ACE');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('asrock-z490-taichi', 'ASRock', 'Z490 Taichi', '2', 'LGA1200', '128 GB', 'ASRock Z490 Taichi');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('gigabyte-z490-vision-d', 'Gigabyte', 'Z490 VISION D', '2', 'LGA1200', '128 GB', 'Gigabyte Z490 VISION D');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('gigabyte-z490-aorus-elite', 'Gigabyte', 'Z490 AORUS ELITE', '2', 'LGA1200', '128 GB', 'Gigabyte Z490 AORUS ELITE');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('asus-proart-z490-creator-10g', 'Asus', 'ProART Z490-CREATOR 10G', '2', 'LGA1200', '128 GB', 'Asus ProART Z490-CREATOR 10G');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('asus-rog-strix-z490-g-gaming-(wi-fi)', 'Asus', 'ROG STRIX Z490-G GAMING (WI-FI)', '2', 'LGA1200', '128 GB', 'Asus ROG STRIX Z490-G GAMING (WI-FI)');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('asus-rog-strix-z490-g-gaming', 'Asus', 'ROG STRIX Z490-G GAMING', '2', 'LGA1200', '128 GB', 'Asus ROG STRIX Z490-G GAMING');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('msi-meg-z490i-unify', 'MSI', 'MEG Z490I UNIFY', '2', 'LGA1200', '64 GB', 'MSI MEG Z490I UNIFY');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('gigabyte-z490i-aorus-ultra', 'Gigabyte', 'Z490I AORUS ULTRA', '2', 'LGA1200', '64 GB', 'Gigabyte Z490I AORUS ULTRA');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('asus-rog-strix-z490-i-gaming', 'Asus', 'ROG STRIX Z490-I GAMING', '2', 'LGA1200', '64 GB', 'Asus ROG STRIX Z490-I GAMING');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('asrock-z490m-pro4', 'ASRock', 'Z490M Pro4', '2', 'LGA1200', '128 GB', 'ASRock Z490M Pro4');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('asrock-z490m-itx/ac', 'ASRock', 'Z490M-ITX/ac', '2', 'LGA1200', '64 GB', 'ASRock Z490M-ITX/ac');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('asus-prime-z490m-plus', 'Asus', 'PRIME Z490M-PLUS', '2', 'LGA1200', '128 GB', 'Asus PRIME Z490M-PLUS');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('gigabyte-a520m-s2h', 'Gigabyte', 'A50M SH', '2', 'AM4', '64 GB', 'Gigabyte A520M S2H');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('asrock-a520m-hdvp', 'ASRock', 'A50M-HDVP', '2', 'AM4', '64 GB', 'ASRock A520M-HDVP');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('gigabyte-a520m-aorus-elite', 'Gigabyte', 'A520M AORUS ELITE', '1', 'AM4', '128 GB', 'Gigabyte A520M AORUS ELITE');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('asus-prime-a520m-e', 'Asus', 'PRIME A520M-E', '1', 'AM4', '64 GB', 'Asus PRIME A520M-E');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('asus-prime-a520m-k', 'Asus', 'PRIME A520M-K', '1', 'AM4', '64 GB', 'Asus PRIME A520M-K');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('msi-b360m-mortar', 'MSI', 'B360M MORTAR', '1', 'LGA1151', '64 GB', 'MSI B360M MORTAR');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('asus-rog-strix-b550-e-gaming', 'Asus', 'ROG STRIX B550-E GAMING', '1', 'AM4', '128 GB', 'Asus ROG STRIX B550-E GAMING');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('gigabyte-x570-aorus-elite', 'Gigabyte', 'X570 AORUS ELITE', '1', 'AM4', '128 GB', 'Gigabyte X570 AORUS ELITE');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('asus-pro-ws-x570-ace', 'Asus', 'Pro WS X570-ACE', '1', 'AM4', '128 GB', 'Asus Pro WS X570-ACE');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('asus-rog-maximus-xi-hero-(wi-fi)', 'Asus', 'ROG MAXIMUS XI HERO (WI-FI)', 'Z390', 'LGA1151', '128 GB', 'Asus ROG MAXIMUS XI HERO (WI-FI)');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('asus-rog-maximus-xi-formula', 'Asus', 'ROG MAXIMUS XI FORMULA', 'Z390', 'LGA1151', '128 GB', 'Asus ROG MAXIMUS XI FORMULA');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('asus-rog-maximus-xi-hero', 'Asus', 'ROG MAXIMUS XI HERO', 'Z390', 'LGA1151', '128 GB', 'Asus ROG MAXIMUS XI HERO');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('asus-rog-maximus-x-formula', 'Asus', 'ROG MAXIMUS X FORMULA', 'Z370', 'LGA1151', '64 GB', 'Asus ROG MAXIMUS X FORMULA');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('asus-rog-maximus-x-hero-(wi-fi-ac)', 'Asus', 'ROG MAXIMUS X HERO (WI-FI AC)', 'Z370', 'LGA1151', '64 GB', 'Asus ROG MAXIMUS X HERO (WI-FI AC)');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('asus-rog-maximus-x-hero', 'Asus', 'ROG MAXIMUS X HERO', 'Z370', 'LGA1151', '64 GB', 'Asus ROG MAXIMUS X HERO');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('asus-rog-maximus-x-code', 'Asus', 'ROG MAXIMUS X CODE', 'Z370', 'LGA1151', '64 GB', 'Asus ROG MAXIMUS X CODE');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('asus-rog-maximus-xi-extreme', 'Asus', 'ROG MAXIMUS XI EXTREME', 'Z390', 'LGA1151', '128 GB', 'Asus ROG MAXIMUS XI EXTREME');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('asus-rog-maximus-xi-apex', 'Asus', 'ROG MAXIMUS XI APEX', 'Z390', 'LGA1151', '64 GB', 'Asus ROG MAXIMUS XI APEX');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('msi-a320m-pro-m2-v2', 'MSI', 'A320M PRO-M2 V2', '1', 'AM4', '32 GB', 'MSI A320M PRO-M2 V2');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('msi-a320m-pro-vd/s', 'MSI', 'A320M PRO-VD/S', '1', 'AM4', '32 GB', 'MSI A320M PRO-VD/S');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('msi-a320m-a-pro-max', 'MSI', 'A320M-A PRO MAX', '1', 'AM4', '32 GB', 'MSI A320M-A PRO MAX');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('msi-a320m-a-pro', 'MSI', 'A320M-A PRO', '1', 'AM4', '64 GB', 'MSI A320M-A PRO');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('asrock-a320m-dvs-r4.0', 'ASRock', 'A320M-DVS R4.0', '1', 'AM4', '32 GB', 'ASRock A320M-DVS R4.0');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('gigabyte-a520-aorus-elite', 'Gigabyte', 'A520 AORUS ELITE', '1', 'AM4', '128 GB', 'Gigabyte A520 AORUS ELITE');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('gigabyte-a520i-ac', 'Gigabyte', 'A520I AC', '1', 'AM4', '64 GB', 'Gigabyte A520I AC');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('msi-a520m-a-pro', 'MSI', 'A520M-A PRO', '1', 'AM4', '64 GB', 'MSI A520M-A PRO');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('asrock-a520m-hdvp/dash', 'ASRock', 'A520M-HDVP/DASH', '1', 'AM4', '64 GB', 'ASRock A520M-HDVP/DASH');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('asrock-a520m-itx/ac', 'ASRock', 'A520M-ITX/ac', '1', 'AM4', '64 GB', 'ASRock A520M-ITX/ac');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('asus-tuf-gaming-a520m-plus', 'Asus', 'TUF GAMING A520M-PLUS', '1', 'AM4', '128 GB', 'Asus TUF GAMING A520M-PLUS');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('asus-strix-b350-f-gaming', 'Asus', 'STRIX B350-F GAMING', '1', 'AM4', '64 GB', 'Asus STRIX B350-F GAMING');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('gigabyte-b360-aorus-gaming-3', 'Gigabyte', 'B360 AORUS GAMING 3', '1', 'LGA1151', '64 GB', 'Gigabyte B360 AORUS GAMING 3');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('asus-rog-strix-b360-f-gaming', 'Asus', 'ROG STRIX B360-F GAMING', '1', 'LGA1151', '64 GB', 'Asus ROG STRIX B360-F GAMING');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('asus-rog-strix-b360-g-gaming', 'Asus', 'ROG STRIX B360-G GAMING', '1', 'LGA1151', '64 GB', 'Asus ROG STRIX B360-G GAMING');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('asus-rog-strix-b360-i-gaming', 'Asus', 'ROG STRIX B360-I GAMING', '1', 'LGA1151', '32 GB', 'Asus ROG STRIX B360-I GAMING');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('msi-b360m-bazooka', 'MSI', 'B360M BAZOOKA', '1', 'LGA1151', '64 GB', 'MSI B360M BAZOOKA');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('gigabyte-b360m-aorus-gaming-3', 'Gigabyte', 'B360M AORUS GAMING 3', '1', 'LGA1151', '64 GB', 'Gigabyte B360M AORUS GAMING 3');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('gigabyte-b360m-d2v', 'Gigabyte', 'B360M D2V', '1', 'LGA1151', '32 GB', 'Gigabyte B360M D2V');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('asus-rog-strix-b365-f-gaming', 'Asus', 'ROG STRIX B365-F GAMING', '1', 'LGA1151', '64 GB', 'Asus ROG STRIX B365-F GAMING');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('msi-mag-b365m-mortar', 'MSI', 'MAG B365M MORTAR', '1', 'LGA1151', '64 GB', 'MSI MAG B365M MORTAR');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('asus-prime-b365m-k', 'Asus', 'PRIME B365M-K', '1', 'LGA1151', '32 GB', 'Asus PRIME B365M-K');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('msi-b365m-pro-vh', 'MSI', 'B365M-PRO-VH', '1', 'LGA1151', '32 GB', 'MSI B365M-PRO-VH');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('asrock-z490-phantom-gaming-itx/tb3', 'ASRock', 'Z490 Phantom Gaming-ITX/TB3', '1', 'LGA1200', '64 GB', 'ASRock Z490 Phantom Gaming-ITX/TB3');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('msi-b450-gaming-plus-max', 'MSI', 'B450 Gaming Plus MAX', '1', 'AM4', '64 GB', 'MSI B450 Gaming Plus MAX');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('asrock-b450-steel-legend', 'ASRock', 'B450 Steel Legend', '1', 'AM4', '64 GB', 'ASRock B450 Steel Legend');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('asus-rog-strix-b450-f-gaming', 'Asus', 'ROG STRIX B450-F GAMING', '1', 'AM4', '64 GB', 'Asus ROG STRIX B450-F GAMING');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('msi-b450m-pro-m2-max', 'MSI', 'B450M PRO-M2 MAX', '1', 'AM4', '32 GB', 'MSI B450M PRO-M2 MAX');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('msi-b450m-pro-vdh-max', 'MSI', 'B450M PRO-VDH MAX', '1', 'AM4', '64 GB', 'MSI B450M PRO-VDH MAX');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('gigabyte-b450m-aorus-elite', 'Gigabyte', 'B450M AORUS ELITE', '1', 'AM4', '128 GB', 'Gigabyte B450M AORUS ELITE');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('msi-b450m-pro-m2-v2', 'MSI', 'B450M PRO-M2 V2', '1', 'AM4', '32 GB', 'MSI B450M PRO-M2 V2');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('msi-b450m-a-pro-max', 'MSI', 'B450M-A PRO MAX', '1', 'AM4', '32 GB', 'MSI B450M-A PRO MAX');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('gigabyte-b460-hd3', 'Gigabyte', 'B460 HD3', '1', 'LGA1200', '128 GB', 'Gigabyte B460 HD3');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('msi-b460m-pro-vdh-wifi', 'MSI', 'B460M PRO-VDH WIFI', '1', 'LGA1200', '128 GB', 'MSI B460M PRO-VDH WIFI');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('gigabyte-b460m-aorus-pro', 'Gigabyte', 'B460M AORUS PRO', '1', 'LGA1200', '128 GB', 'Gigabyte B460M AORUS PRO');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('gigabyte-b460m-d2v', 'Gigabyte', 'B460M D2V', '1', 'LGA1200', '64 GB', 'Gigabyte B460M D2V');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('msi-b460m-a-pro', 'MSI', 'B460M-A PRO', '1', 'LGA1200', '64 GB', 'MSI B460M-A PRO');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('asrock-b460m-itx/ac', 'ASRock', 'B460M-ITX/ac', '1', 'LGA1200', '64 GB', 'ASRock B460M-ITX/ac');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('asus-prime-b460m-k', 'Asus', 'PRIME B460M-K', '1', 'LGA1200', '64 GB', 'Asus PRIME B460M-K');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('asus-prime-b460-plus', 'Asus', 'PRIME B460-PLUS', '1', 'LGA1200', '128 GB', 'Asus PRIME B460-PLUS');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('msi-mag-b550-tomahawk', 'MSI', 'MAG B550 TOMAHAWK', '1', 'AM4', '128 GB', 'MSI MAG B550 TOMAHAWK');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('gigabyte-b550-aorus-pro-ac', 'Gigabyte', 'B550 AORUS PRO AC', '1', 'AM4', '128 GB', 'Gigabyte B550 AORUS PRO AC');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('gigabyte-b550-vision-d', 'Gigabyte', 'B550 VISION D', '1', 'AM4', '128 GB', 'Gigabyte B550 VISION D');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('gigabyte-b550-gaming-x', 'Gigabyte', 'B550 GAMING X', '1', 'AM4', '128 GB', 'Gigabyte B550 GAMING X');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('asrock-b550-extreme4', 'ASRock', 'B550 Extreme4', '1', 'AM4', '128 GB', 'ASRock B550 Extreme4');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('asrock-b550-pg-velocita', 'ASRock', 'B550 PG Velocita', '1', 'AM4', '128 GB', 'ASRock B550 PG Velocita');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('gigabyte-b550-aorus-pro-ax', 'Gigabyte', 'B550 AORUS PRO AX', '1', 'AM4', '128 GB', 'Gigabyte B550 AORUS PRO AX');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('gigabyte-b550m-ds3h', 'Gigabyte', 'B550M DS3H', '1', 'AM4', '128 GB', 'Gigabyte B550M DS3H');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('msi-b550m-pro-vdh-wifi', 'MSI', 'B550M PRO-VDH WIFI', '1', 'AM4', '128 GB', 'MSI B550M PRO-VDH WIFI');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('msi-mag-b550m-mortar-wifi', 'MSI', 'MAG B550M MORTAR WIFI', '1', 'AM4', '128 GB', 'MSI MAG B550M MORTAR WIFI');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('asus-prime-b550m-a', 'Asus', 'PRIME B550M-A', '1', 'AM4', '128 GB', 'Asus PRIME B550M-A');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('asus-prime-b550m-k', 'Asus', 'PRIME B550M-K', '1', 'AM4', '128 GB', 'Asus PRIME B550M-K');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('asus-tuf-gaming-b550m-plus', 'Asus', 'TUF GAMING B550M-PLUS', '1', 'AM4', '128 GB', 'Asus TUF GAMING B550M-PLUS');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('asus-tuf-gaming-b550-plus', 'Asus', 'TUF GAMING B550-PLUS', '1', 'AM4', '128 GB', 'Asus TUF GAMING B550-PLUS');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('asrock-h310cm-hdv', 'ASRock', 'H30CM-HDV', '1', 'LGA1151', '32 GB', 'ASRock H310CM-HDV');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('gigabyte-h310m-s2h', 'Gigabyte', 'H30M S2H', '1', 'LGA1151', '32 GB', 'Gigabyte H310M S2H');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('msi-h310m-pro-vd', 'MSI', 'H30M PRO-VD', '1', 'LGA1151', '32 GB', 'MSI H310M PRO-VD');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('msi-h310m-pro-d', 'MSI', 'H30M PRO-D', '1', 'LGA1151', '32 GB', 'MSI H310M PRO-D');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('msi-h310m-pro-vhl', 'MSI', 'H30M PRO-VHL', '1', 'LGA1151', '32 GB', 'MSI H310M PRO-VHL');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('msi-h310m-pro-vl', 'MSI', 'H30M PRO-VL', '1', 'LGA1151', '32 GB', 'MSI H310M PRO-VL');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('asus-prime-h310m-e-r2.0', 'Asus', 'PRIME H30M-E R2.0', '1', 'LGA1151', '32 GB', 'Asus PRIME H310M-E R2.0');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('asus-prime-h310m-e', 'Asus', 'PRIME H30M-E', '1', 'LGA1151', '32 GB', 'Asus PRIME H310M-E');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('gigabyte-h410m-s2h', 'Gigabyte', 'H40M S2H', '1', 'LGA1200', '64 GB', 'Gigabyte H410M S2H');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('msi-h410m-pro', 'MSI', 'H40M PRO', '1', 'LGA1200', '64 GB', 'MSI H410M PRO');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('gigabyte-h410m-h', 'Gigabyte', 'H40M H', '1', 'LGA1200', '64 GB', 'Gigabyte H410M H');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('msi-h410m-a-pro', 'MSI', 'H40M-A PRO', '1', 'LGA1200', '64 GB', 'MSI H410M-A PRO');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('asrock-h410m-hdvp', 'ASRock', 'H40M-HDVP', '1', 'LGA1200', '64 GB', 'ASRock H410M-HDVP');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('msi-mpg-x570-gaming-plus', 'MSI', 'MPG X570 GAMING PLUS', '1', 'AM4', '128 GB', 'MSI MPG X570 GAMING PLUS');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('gigabyte-x570-i-aorus-pro-wifi', 'Gigabyte', 'X570 I AORUS PRO WIFI', '1', 'AM4', '64 GB', 'Gigabyte X570 I AORUS PRO WIFI');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('gigabyte-x570-aorus-xtreme', 'Gigabyte', 'X570 AORUS XTREME', '1', 'AM4', '128 GB', 'Gigabyte X570 AORUS XTREME');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('asus-prime-x570-p', 'Asus', 'PRIME X570-P', '1', 'AM4', '128 GB', 'Asus PRIME X570-P');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('asus-rog-strix-z370-i-gaming', 'Asus', 'ROG Strix Z370-I Gaming', '1', 'LGA1151', '32 GB', 'Asus ROG Strix Z370-I Gaming');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('gigabyte-z390-aorus-pro-wifi', 'Gigabyte', 'Z390 AORUS PRO WIFI', '1', 'LGA1151', '128 GB', 'Gigabyte Z390 AORUS PRO WIFI');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('gigabyte-z390-ud', 'Gigabyte', 'Z390 UD', '1', 'LGA1151', '128 GB', 'Gigabyte Z390 UD');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('gigabyte-z390-i-aorus-pro-wifi', 'Gigabyte', 'Z390 I AORUS PRO WIFI', '1', 'LGA1151', '64 GB', 'Gigabyte Z390 I AORUS PRO WIFI');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('gigabyte-z390-aorus-elite', 'Gigabyte', 'Z390 AORUS ELITE', '1', 'LGA1151', '128 GB', 'Gigabyte Z390 AORUS ELITE');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('gigabyte-z390-aorus-ultra', 'Gigabyte', 'Z390 AORUS ULTRA', '1', 'LGA1151', '128 GB', 'Gigabyte Z390 AORUS ULTRA');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('msi-mpg-z390-gaming-pro-carbon', 'MSI', 'MPG Z390 GAMING PRO CARBON', '1', 'LGA1151', '128 GB', 'MSI MPG Z390 GAMING PRO CARBON');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('msi-meg-z390-ace', 'MSI', 'MEG Z390 ACE', '1', 'LGA1151', '128 GB', 'MSI MEG Z390 ACE');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('asrock-z390-taichi', 'ASRock', 'Z390 Taichi', '1', 'LGA1151', '128 GB', 'ASRock Z390 Taichi');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('msi-meg-z390-godlike', 'MSI', 'MEG Z390 GODLIKE', '1', 'LGA1151', '128 GB', 'MSI MEG Z390 GODLIKE');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('asrock-z390-phantom-gaming-7', 'ASRock', 'Z390 PHANTOM GAMING 7', '1', 'LGA1151', '128 GB', 'ASRock Z390 PHANTOM GAMING 7');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('gigabyte-z390-aorus-xtreme-waterforce', 'Gigabyte', 'Z390 AORUS XTREME WATERFORCE', '1', 'LGA1151', '128 GB', 'Gigabyte Z390 AORUS XTREME WATERFORCE');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('asus-ws-z390-pro', 'Asus', 'WS Z390 PRO', '1', 'LGA1151', '128 GB', 'Asus WS Z390 PRO');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('asrock-z390-taichi-ultimate', 'ASRock', 'Z390 Taichi Ultimate', '1', 'LGA1151', '128 GB', 'ASRock Z390 Taichi Ultimate');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('asrock-z390-phantom-gaming-6', 'ASRock', 'Z390 Phantom Gaming 6', '1', 'LGA1151', '128 GB', 'ASRock Z390 Phantom Gaming 6');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('asus-prime-z390-a', 'Asus', 'PRIME Z390-A', '1', 'LGA1151', '128 GB', 'Asus PRIME Z390-A');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('asus-rog-strix-z390-e-gaming', 'Asus', 'ROG STRIX Z390-E GAMING', '1', 'LGA1151', '128 GB', 'Asus ROG STRIX Z390-E GAMING');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('asus-rog-strix-z390-i-gaming', 'Asus', 'ROG STRIX Z390-I GAMING', '1', 'LGA1151', '64 GB', 'Asus ROG STRIX Z390-I GAMING');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('msi-mpg-z390m-gaming-edge-ac', 'MSI', 'MPG Z390M GAMING EDGE AC', '1', 'LGA1151', '128 GB', 'MSI MPG Z390M GAMING EDGE AC');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('asus-tuf-z390-plus-gaming', 'Asus', 'TUF Z390-PLUS GAMING', '1', 'LGA1151', '128 GB', 'Asus TUF Z390-PLUS GAMING');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('msi-mpg-z490-gaming-carbon-wifi', 'MSI', 'MPG Z490 GAMING CARBON WIFI', '1', 'LGA1200', '128 GB', 'MSI MPG Z490 GAMING CARBON WIFI');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('gigabyte-z490-gaming-x', 'Gigabyte', 'Z490 GAMING X', '1', 'LGA1200', '128 GB', 'Gigabyte Z490 GAMING X');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('asrock-z490-pro4', 'ASRock', 'Z490 Pro4', '1', 'LGA1200', '128 GB', 'ASRock Z490 Pro4');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('gigabyte-z490-aorus-xtreme', 'Gigabyte', 'Z490 AORUS XTREME', '1', 'LGA1200', '128 GB', 'Gigabyte Z490 AORUS XTREME');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('gigabyte-z490-aorus-ultra-g2', 'Gigabyte', 'Z490 AORUS ULTRA G2', '1', 'LGA1200', '128 GB', 'Gigabyte Z490 AORUS ULTRA G2');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('msi-z490-a-pro', 'MSI', 'Z490-A PRO', '1', 'LGA1200', '128 GB', 'MSI Z490-A PRO');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('asus-rog-strix-z490-a-gaming', 'Asus', 'ROG STRIX Z490-A GAMING', '1', 'LGA1200', '128 GB', 'Asus ROG STRIX Z490-A GAMING');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('asus-tuf-gaming-z490-plus-(wi-fi)', 'Asus', 'TUF GAMING Z490-PLUS (WI-FI)', '1', 'LGA1200', '128 GB', 'Asus TUF GAMING Z490-PLUS (WI-FI)');
INSERT IGNORE INTO `pc_parts_picker`.mainboard VALUES ('asus-tuf-gaming-z490-plus', 'Asus', 'TUF GAMING Z490-PLUS', '1', 'LGA1200', '128 GB', 'Asus TUF GAMING Z490-PLUS');